package ${pojo.getPackageName()}.service;
// Generated by bo.wang with ${version}

<#assign classbody>
<#assign declarationName = pojo.importType(pojo.getDeclarationName())>/**
 * Home object for domain model class ${declarationName}.
 * @see ${pojo.getQualifiedDeclarationName()}
 * @author Hibernate Tools
 */
public interface ${declarationName}Service extends IService{
	public static final String BEAN_ID="${pojo.getDeclarationNameFirstLetterLower()}Service";
	
	public DaoPage find${declarationName}ByParams(Map params, Integer pageIndex,Integer pageSize);
	
	public List find${declarationName}ByParams(Map params);
	
	public void save${declarationName}DataListsMap(Map dataListsMap);
	
	List<${declarationName}InParam> load${declarationName}(Map<String, Object> map);
	
	public ${declarationName}InParam convert${declarationName}ToInParam(${declarationName} model);
	
	public ${declarationName} convert${declarationName}InParamToEntity(${declarationName}InParam inParam);
}
</#assign>
import java.util.List;
import java.util.Map;

import com.ling2.core.commons.support.DaoPage;
import com.ling2.core.service.IService;
import ${pojo.getPackageName()}.model.${declarationName};
import ${pojo.getPackageName()}.model.${declarationName}InParam;
import ${pojo.getPackageName()}.dao.${declarationName}Dao;
${classbody}
