package com.deloitte.tms.vat.trnsctrecog.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.deloitte.tms.base.masterdata.model.BaseOrg;
import com.deloitte.tms.base.masterdata.model.Customer;
import com.deloitte.tms.base.masterdata.model.TmsMdTaxTrxType;
import com.deloitte.tms.pl.core.commons.annotation.ModelProperty;
import com.deloitte.tms.pl.core.hibernate.identifier.Ling2UUIDGenerator;
import com.deloitte.tms.pl.core.model.impl.BaseEntity;

/**
 * TmsCrvatTrxAffirm generated by ling autoproject
 */
@Entity
@Table(name=TmsCrvatTrxAffirm.TABLE)
public class TmsCrvatTrxAffirm extends BaseEntity {

	public static final String TABLE = "TMS_CRVAT_TRX_AFFIRM";
	public static final String SEQ = TABLE;

    @Id
	@GenericGenerator(name=SEQ+"_GENERATOR",strategy=Ling2UUIDGenerator.STRATEGY_NAME,parameters={@Parameter(name="pkColumnValue",value=SEQ)})
	@GeneratedValue(strategy = GenerationType.TABLE, generator = SEQ+"_GENERATOR")

    @Column(name="TRX_AFFIRM_ID", length=36)
	@ModelProperty(comment="交易认定后分录流水ID")
	private String id;

    @Column(name="SALES_TRX_ID", length=36)
	@ModelProperty(comment="交易汇总数据ID")
	private String salasTrxId;

    @Column(name="TRX_AFFRIM_DATE", length=7)
	@ModelProperty(comment="交易认定日期")
	private Date trxAffrimDate;

    @Column(name="TRX_DATE", length=7)
	@ModelProperty(comment="交易日期")
	private Date trxDate;

    @Column(name="CUSTOMER_ID", length=36)
	@ModelProperty(comment="客户ID")
	private String customerId;

    @Column(name="TAX_TRX_TYPE_ID", length=36)
	@ModelProperty(comment="涉税交易类型ID")
	private String taxTrxTypeId;

    @Column(name="PERIOD_NAME", length=100)
	@ModelProperty(comment="所属期间(1.2.3月)")
	private String periodName;

    @Column(name="ORG_ID", length=100)
	@ModelProperty(comment="交易组织")
	private String orgId;

    @Column(name="ORG_CODE", length=100)
	@ModelProperty(comment="交易组织代码")
	private String orgCode;

    @Column(name="ORG_NAME", length=500)
	@ModelProperty(comment="交易组织名称")
	private String orgName;

    @Column(name="DEPT_ID", length=100)
	@ModelProperty(comment="交易部门")
	private String deptId;

    @Column(name="TRX_BATCH_NUM", length=100)
	@ModelProperty(comment="交易批次号")
	private String trxBatchNum;

    @Column(name="TRX_NUMBER", length=100)
	@ModelProperty(comment="交易流水号")
	private String trxNumber;

    @Column(name="ACCOUNT_DATE", length=7)
	@ModelProperty(comment="记账日期")
	private Date accountDate;

    @Column(name="BSN_COMBINATION_ID", length=36)
	@ModelProperty(comment="业务数据结构组合ID")
	private String bsnCombinationId;

    @Column(name="BSN_COMBINATION_CODE", length=2000)
	@ModelProperty(comment="业务数据结构组合代码")
	private String bsnCombinationCode;

    @Column(name="BSN_COMBINATION_NAME", length=2000)
	@ModelProperty(comment="业务数据结构组合说明")
	private String bsnCombinationName;

    @Column(name="ACCD_COMBINATION_ID", length=36)
	@ModelProperty(comment="会计科目结构组合ID")
	private String accdCombinationId;

    @Column(name="ACCD_COMBINATION_NAME", length=2000)
	@ModelProperty(comment="会计科目结构组合说明")
	private String accdCombinationName;

    @Column(name="ACCD_COMBINATION_CODE", length=2000)
	@ModelProperty(comment="会计科目结构组合代码")
	private String accdCombinationCode;

    @Column(name="ORIGINAL_CURRENCY_CODE", length=100)
	@ModelProperty(comment="原币种_枚举值")
	private String originalCurrencyCode;

    @Column(name="ORIGINAL_CURRENCY_AMOUNT_DR")
	@ModelProperty(comment="原币借方金额")
	private Long originalCurrencyAmountDr;

    @Column(name="ORIGINAL_CURRENCY_AMOUNT_CR")
	@ModelProperty(comment="原币贷方金额")
	private Long originalCurrencyAmountCr;

    @Column(name="CURRENCY_CODE", length=100)
	@ModelProperty(comment="本位币_枚举值")
	private String currencyCode;

    @Column(name="CURRENCY_AMOUNT_DR")
	@ModelProperty(comment="本位币借方金额")
	private Long currencyAmountDr;

    @Column(name="CURRENCY_AMOUNT_CR")
	@ModelProperty(comment="本位币贷方金额")
	private Long currencyAmountCr;

    @Column(name="ACCOUNT_RATE")
	@ModelProperty(comment="核算汇率")
	private Long accountRate;

    @Column(name="EXCHANGE_RATE")
	@ModelProperty(comment="开票汇率")
	private Long exchangeRate;

    @Column(name="RATE_TYPE", length=100)
	@ModelProperty(comment="汇率类型")
	private String rateType;

    @Column(name="RATE_DATE", length=7)
	@ModelProperty(comment="汇率日期")
	private Date rateDate;

    @Column(name="IMP_TRX_DATE", length=7)
	@ModelProperty(comment="导入日期")
	private Date impTrxDate;

    @Column(name="AFFRIM_TYPE", length=100)
	@ModelProperty(comment="交易认定类型(系统认定/手工认定)_枚举值")
	private String affrimType;

    @Column(name="INVOICING_RULE", length=100)
	@ModelProperty(comment="开票规则 (1:专票和普票  2:仅普票 3:不可开票)")
	private String invoicingRule;

    @Column(name="SPIT_RULE_CODE", length=36)
	@ModelProperty(comment="价税分离核算规则")
	private String spitRuleCode;

    @Column(name="IS_ACCOUNT", length=10)
	@ModelProperty(comment="是否核算")
	private Boolean isAccount;

    @Column(name="INVOICING_TYPE", length=100)
	@ModelProperty(comment="开票方式_枚举值(属地/汇总)")
	private String invoicingType;

    @Column(name="TAX_BASE_ID", length=36)
	@ModelProperty(comment="计税基础ID")
	private String taxBaseId;

    @Column(name="TAX_BASE_CODE", length=100)
	@ModelProperty(comment="计税基础代码")
	private String taxBaseCode;

    @Column(name="TAX_BASE_NAME", length=500)
	@ModelProperty(comment="计税基础名称")
	private String taxBaseName;

    @Column(name="TAX_RATE")
	@ModelProperty(comment="税率")
	private Long taxRate;

    @Column(name="TRX_AFFIRM_SETTING_ID", length=100)
	@ModelProperty(comment="涉税交易认定设置规则ID")
	private String trxAffirmSettingId;

    @Column(name="SOURCE_CODE", length=100)
	@ModelProperty(comment="来源代码")
	private String sourceCode;

    @Column(name="SOURCE_TRX_HEADER_ID", length=100)
	@ModelProperty(comment="源分录流水头ID")
	private String sourceTrxHeaderId;

    @Column(name="SOURCE_TRX_LINE_ID", length=100)
	@ModelProperty(comment="源分录流水行ID")
	private String sourceTrxLineId;

    @Column(name="SOURCE_TRX_LINE_TYPE", length=100)
	@ModelProperty(comment="源分录流水行类型")
	private String sourceTrxLineType;

    @Column(name="TAX_SETTING_METHOD", length=100)
	@ModelProperty(comment="计税方法(一般计税/免税/简易征收)")
	private String taxSettingMethod;

    @Column(name="CUST_REGISTRATION_NUMBER", length=100)
	@ModelProperty(comment="购方证件号码")
	private String custRegistrationNumber;

    @Column(name="CUST_REGISTRATION_CODE", length=100)
	@ModelProperty(comment="购方证件类型_枚举值")
	private String custRegistrationCode;

    @Column(name="LEGAL_ENTITY_TYPE", length=100)
	@ModelProperty(comment="纳税人类型(一般纳税人/小规模纳税人/非增值税纳税人)")
	private String legalEntityType;

    @Column(name="LEGAL_ENTITY_ID", length=36)
	@ModelProperty(comment="销方ID")
	private String legalEntityId;

    @Column(name="LEGAL_ENTITY_CODE", length=100)
	@ModelProperty(comment="销方CODE")
	private String legalEntityCode;

    @Column(name="LEGAL_ENTITY_NAME", length=500)
	@ModelProperty(comment="销方纳税名称")
	private String legalEntityName;

    @Column(name="REGISTRATION_NUMBER", length=100)
	@ModelProperty(comment="销方证件号码")
	private String registrationNumber;

    @Column(name="REGISTRATION_CODE", length=100)
	@ModelProperty(comment="销方证件类型_枚举值")
	private String registrationCode;

    @Column(name="CUST_BANK_BRANCH_NAME", length=500)
	@ModelProperty(comment="购方开户行")
	private String custBankBranchName;

    @Column(name="CUST_BANK_ACCOUNT_NUM", length=100)
	@ModelProperty(comment="购方开户账号")
	private String custBankAccountNum;

    @Column(name="CUST_BANK_ACCOUNT_TYPE", length=100)
	@ModelProperty(comment="购方开户账号类型_枚举值")
	private String custBankAccountType;

    @Column(name="CUST_CONTACT_PHONE", length=100)
	@ModelProperty(comment="购方联系电话")
	private String custContactPhone;

    @Column(name="CUST_CONTACT_NAME", length=100)
	@ModelProperty(comment="购方联系人名称")
	private String custContactName;

    @Column(name="CUST_REGISTRATION_ADDRESS", length=500)
	@ModelProperty(comment="客户地址")
	private String custRegistrationAddress;

    @Column(name="INVENTORY_ITEM_ID", length=100)
	@ModelProperty(comment="货物ID")
	private String inventoryItemId;

    @Column(name="INVENTORY_ITEM_NUMBER", length=100)
	@ModelProperty(comment="商品及服务编码")
	private String inventoryItemNumber;

    @Column(name="INVENTORY_ITEM_DESCRIPTON", length=2000)
	@ModelProperty(comment="商品及服务名称")
	private String inventoryItemDescripton;

    @Column(name="INVENTORY_ITEM_MODELS", length=500)
	@ModelProperty(comment="规格型号")
	private String inventoryItemModels;

    @Column(name="UOM_CODE", length=100)
	@ModelProperty(comment="单位代码")
	private String uomCode;

    @Column(name="UOM_CODE_DESCRIPTON", length=100)
	@ModelProperty(comment="单位名称")
	private String uomCodeDescripton;

    @Column(name="INVENTORY_ITEM_QTY")
	@ModelProperty(comment="货物数量")
	private Long inventoryItemQty;

    @Column(name="PRICE_OF_UNIT")
	@ModelProperty(comment="单价")
	private Long priceOfUnit;

    @Column(name="IS_APPOINT_INVOICE", length=10)
	@ModelProperty(comment="是否预约开票")
	private Boolean isAppointInvoice;

    @Column(name="AUTOREVERSE_FLAG", length=10)
	@ModelProperty(comment="明细冲账标识(Y-冲账/N-正常/R-被冲账)")
	private Boolean autoreverseFlag;

    @Column(name="REVERSE_TYPE_CODE", length=100)
	@ModelProperty(comment="冲账类型代码(T-当日冲账/R-隔日冲账/B-跨年冲账)")
	private String reverseTypeCode;

    @Column(name="REVERSE_TYPE_NAME", length=100)
	@ModelProperty(comment="冲账类型名称(T-当日冲账/R-隔日冲账/B-跨年冲账)")
	private String reverseTypeName;

    @Column(name="REVERSAL_DATE", length=7)
	@ModelProperty(comment="被冲/冲账交易日期")
	private Date reversalDate;

    @Column(name="REVERSAL_TRX_NUMBER", length=100)
	@ModelProperty(comment="被冲/冲账交易日志号")
	private String reversalTrxNumber;

    @Column(name="APPOINT_INVOICE_ORG_NAME", length=240)
	@ModelProperty(comment="预约开票管理组织名称")
	private String appointInvoiceOrgName;

    @Column(name="APPOINT_INVOICE_ORG_CODE", length=100)
	@ModelProperty(comment="预约开票管理组织代码")
	private String appointInvoiceOrgCode;

    @Column(name="APPOINT_INVOICE_ORG_ID", length=100)
	@ModelProperty(comment="预约开票管理组织ID")
	private String appointInvoiceOrgId;

    @Column(name="CUSTOMER_NUMBER", length=100)
	@ModelProperty(comment="购方编码")
	private String customerNumber;

    @Column(name="CUST_GSN_REGISTRATION_NUMBER", length=100)
	@ModelProperty(comment="购方社会统一信用代码")
	private String custGsnRegistrationNumber;
    
    @ManyToOne
	@Cascade(CascadeType.REFRESH)
	@JoinColumn(name="ORG_ID", insertable=false,updatable=false,nullable=true)
    private BaseOrg baseOrg;
    
    @ManyToOne
    @Cascade(CascadeType.REFRESH)
    @JoinColumn(name="CUSTOMER_ID", insertable=false,updatable=false,nullable=true)
    private Customer customer;
    
    @ManyToOne
    @Cascade(CascadeType.REFRESH)
    @JoinColumn(name="TAX_TRX_TYPE_ID", insertable=false,updatable=false,nullable=true)
    private TmsMdTaxTrxType tmsMdTaxTrxType;

	public BaseOrg getBaseOrg() {
		return baseOrg;
	}

	public void setBaseOrg(BaseOrg baseOrg) {
		this.baseOrg = baseOrg;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getSalasTrxId() {
		return salasTrxId;
	}

	public void setSalasTrxId(String salasTrxId) {
		this.salasTrxId = salasTrxId;
	}

	public Date getTrxAffrimDate() {
		return trxAffrimDate;
	}

	public void setTrxAffrimDate(Date trxAffrimDate) {
		this.trxAffrimDate = trxAffrimDate;
	}

	public Date getTrxDate() {
		return trxDate;
	}

	public void setTrxDate(Date trxDate) {
		this.trxDate = trxDate;
	}

	public String getCustomerId() {
		return customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public String getTaxTrxTypeId() {
		return taxTrxTypeId;
	}

	public void setTaxTrxTypeId(String taxTrxTypeId) {
		this.taxTrxTypeId = taxTrxTypeId;
	}

	public String getPeriodName() {
		return periodName;
	}

	public void setPeriodName(String periodName) {
		this.periodName = periodName;
	}

	public String getOrgId() {
		return orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getDeptId() {
		return deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	public String getTrxBatchNum() {
		return trxBatchNum;
	}

	public void setTrxBatchNum(String trxBatchNum) {
		this.trxBatchNum = trxBatchNum;
	}

	public String getTrxNumber() {
		return trxNumber;
	}

	public void setTrxNumber(String trxNumber) {
		this.trxNumber = trxNumber;
	}

	public Date getAccountDate() {
		return accountDate;
	}

	public void setAccountDate(Date accountDate) {
		this.accountDate = accountDate;
	}

	public String getBsnCombinationId() {
		return bsnCombinationId;
	}

	public void setBsnCombinationId(String bsnCombinationId) {
		this.bsnCombinationId = bsnCombinationId;
	}

	public String getBsnCombinationCode() {
		return bsnCombinationCode;
	}

	public void setBsnCombinationCode(String bsnCombinationCode) {
		this.bsnCombinationCode = bsnCombinationCode;
	}

	public String getBsnCombinationName() {
		return bsnCombinationName;
	}

	public void setBsnCombinationName(String bsnCombinationName) {
		this.bsnCombinationName = bsnCombinationName;
	}

	public String getAccdCombinationId() {
		return accdCombinationId;
	}

	public void setAccdCombinationId(String accdCombinationId) {
		this.accdCombinationId = accdCombinationId;
	}

	public String getAccdCombinationName() {
		return accdCombinationName;
	}

	public void setAccdCombinationName(String accdCombinationName) {
		this.accdCombinationName = accdCombinationName;
	}

	public String getAccdCombinationCode() {
		return accdCombinationCode;
	}

	public void setAccdCombinationCode(String accdCombinationCode) {
		this.accdCombinationCode = accdCombinationCode;
	}

	public String getOriginalCurrencyCode() {
		return originalCurrencyCode;
	}

	public void setOriginalCurrencyCode(String originalCurrencyCode) {
		this.originalCurrencyCode = originalCurrencyCode;
	}

	public Long getOriginalCurrencyAmountDr() {
		return originalCurrencyAmountDr;
	}

	public void setOriginalCurrencyAmountDr(Long originalCurrencyAmountDr) {
		this.originalCurrencyAmountDr = originalCurrencyAmountDr;
	}

	public Long getOriginalCurrencyAmountCr() {
		return originalCurrencyAmountCr;
	}

	public void setOriginalCurrencyAmountCr(Long originalCurrencyAmountCr) {
		this.originalCurrencyAmountCr = originalCurrencyAmountCr;
	}

	public String getCurrencyCode() {
		return currencyCode;
	}

	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}

	public Long getCurrencyAmountDr() {
		return currencyAmountDr;
	}

	public void setCurrencyAmountDr(Long currencyAmountDr) {
		this.currencyAmountDr = currencyAmountDr;
	}

	public Long getCurrencyAmountCr() {
		return currencyAmountCr;
	}

	public void setCurrencyAmountCr(Long currencyAmountCr) {
		this.currencyAmountCr = currencyAmountCr;
	}

	public Long getAccountRate() {
		return accountRate;
	}

	public void setAccountRate(Long accountRate) {
		this.accountRate = accountRate;
	}

	public Long getExchangeRate() {
		return exchangeRate;
	}

	public void setExchangeRate(Long exchangeRate) {
		this.exchangeRate = exchangeRate;
	}

	public String getRateType() {
		return rateType;
	}

	public void setRateType(String rateType) {
		this.rateType = rateType;
	}

	public Date getRateDate() {
		return rateDate;
	}

	public void setRateDate(Date rateDate) {
		this.rateDate = rateDate;
	}

	public Date getImpTrxDate() {
		return impTrxDate;
	}

	public void setImpTrxDate(Date impTrxDate) {
		this.impTrxDate = impTrxDate;
	}

	public String getAffrimType() {
		return affrimType;
	}

	public void setAffrimType(String affrimType) {
		this.affrimType = affrimType;
	}

	public String getInvoicingRule() {
		return invoicingRule;
	}

	public void setInvoicingRule(String invoicingRule) {
		this.invoicingRule = invoicingRule;
	}

	public String getSpitRuleCode() {
		return spitRuleCode;
	}

	public void setSpitRuleCode(String spitRuleCode) {
		this.spitRuleCode = spitRuleCode;
	}

	public Boolean getIsAccount() {
		return isAccount;
	}

	public void setIsAccount(Boolean isAccount) {
		this.isAccount = isAccount;
	}

	public String getInvoicingType() {
		return invoicingType;
	}

	public void setInvoicingType(String invoicingType) {
		this.invoicingType = invoicingType;
	}

	public String getTaxBaseId() {
		return taxBaseId;
	}

	public void setTaxBaseId(String taxBaseId) {
		this.taxBaseId = taxBaseId;
	}

	public String getTaxBaseCode() {
		return taxBaseCode;
	}

	public void setTaxBaseCode(String taxBaseCode) {
		this.taxBaseCode = taxBaseCode;
	}

	public String getTaxBaseName() {
		return taxBaseName;
	}

	public void setTaxBaseName(String taxBaseName) {
		this.taxBaseName = taxBaseName;
	}

	public Long getTaxRate() {
		return taxRate;
	}

	public void setTaxRate(Long taxRate) {
		this.taxRate = taxRate;
	}

//	public String getTaxMethod() {
//		return taxMethod;
//	}
//
//	public void setTaxMethod(String taxMethod) {
//		this.taxMethod = taxMethod;
//	}

	public String getSourceCode() {
		return sourceCode;
	}

	public void setSourceCode(String sourceCode) {
		this.sourceCode = sourceCode;
	}

	public String getSourceTrxHeaderId() {
		return sourceTrxHeaderId;
	}

	public void setSourceTrxHeaderId(String sourceTrxHeaderId) {
		this.sourceTrxHeaderId = sourceTrxHeaderId;
	}

	public String getSourceTrxLineId() {
		return sourceTrxLineId;
	}

	public void setSourceTrxLineId(String sourceTrxLineId) {
		this.sourceTrxLineId = sourceTrxLineId;
	}

	public String getSourceTrxLineType() {
		return sourceTrxLineType;
	}

	public void setSourceTrxLineType(String sourceTrxLineType) {
		this.sourceTrxLineType = sourceTrxLineType;
	}

	public String getTaxSettingMethod() {
		return taxSettingMethod;
	}

	public void setTaxSettingMethod(String taxSettingMethod) {
		this.taxSettingMethod = taxSettingMethod;
	}

	public String getCustRegistrationNumber() {
		return custRegistrationNumber;
	}

	public void setCustRegistrationNumber(String custRegistrationNumber) {
		this.custRegistrationNumber = custRegistrationNumber;
	}

	public String getCustRegistrationCode() {
		return custRegistrationCode;
	}

	public void setCustRegistrationCode(String custRegistrationCode) {
		this.custRegistrationCode = custRegistrationCode;
	}

	public String getLegalEntityType() {
		return legalEntityType;
	}

	public void setLegalEntityType(String legalEntityType) {
		this.legalEntityType = legalEntityType;
	}

	public String getLegalEntityId() {
		return legalEntityId;
	}

	public void setLegalEntityId(String legalEntityId) {
		this.legalEntityId = legalEntityId;
	}

	public String getLegalEntityCode() {
		return legalEntityCode;
	}

	public void setLegalEntityCode(String legalEntityCode) {
		this.legalEntityCode = legalEntityCode;
	}

	public String getLegalEntityName() {
		return legalEntityName;
	}

	public void setLegalEntityName(String legalEntityName) {
		this.legalEntityName = legalEntityName;
	}

	public String getRegistrationNumber() {
		return registrationNumber;
	}

	public void setRegistrationNumber(String registrationNumber) {
		this.registrationNumber = registrationNumber;
	}

	public String getRegistrationCode() {
		return registrationCode;
	}

	public void setRegistrationCode(String registrationCode) {
		this.registrationCode = registrationCode;
	}

	public String getCustBankBranchName() {
		return custBankBranchName;
	}

	public void setCustBankBranchName(String custBankBranchName) {
		this.custBankBranchName = custBankBranchName;
	}

	public String getCustBankAccountNum() {
		return custBankAccountNum;
	}

	public void setCustBankAccountNum(String custBankAccountNum) {
		this.custBankAccountNum = custBankAccountNum;
	}

	public String getCustBankAccountType() {
		return custBankAccountType;
	}

	public void setCustBankAccountType(String custBankAccountType) {
		this.custBankAccountType = custBankAccountType;
	}

	public String getCustContactPhone() {
		return custContactPhone;
	}

	public void setCustContactPhone(String custContactPhone) {
		this.custContactPhone = custContactPhone;
	}

	public String getCustContactName() {
		return custContactName;
	}

	public void setCustContactName(String custContactName) {
		this.custContactName = custContactName;
	}

	public String getCustRegistrationAddress() {
		return custRegistrationAddress;
	}

	public void setCustRegistrationAddress(String custRegistrationAddress) {
		this.custRegistrationAddress = custRegistrationAddress;
	}

	public String getInventoryItemId() {
		return inventoryItemId;
	}

	public void setInventoryItemId(String inventoryItemId) {
		this.inventoryItemId = inventoryItemId;
	}

	public String getInventoryItemNumber() {
		return inventoryItemNumber;
	}

	public void setInventoryItemNumber(String inventoryItemNumber) {
		this.inventoryItemNumber = inventoryItemNumber;
	}

	public String getInventoryItemDescripton() {
		return inventoryItemDescripton;
	}

	public void setInventoryItemDescripton(String inventoryItemDescripton) {
		this.inventoryItemDescripton = inventoryItemDescripton;
	}

	public String getInventoryItemModels() {
		return inventoryItemModels;
	}

	public void setInventoryItemModels(String inventoryItemModels) {
		this.inventoryItemModels = inventoryItemModels;
	}

	public String getUomCode() {
		return uomCode;
	}

	public void setUomCode(String uomCode) {
		this.uomCode = uomCode;
	}

	public String getUomCodeDescripton() {
		return uomCodeDescripton;
	}

	public void setUomCodeDescripton(String uomCodeDescripton) {
		this.uomCodeDescripton = uomCodeDescripton;
	}

	public Long getInventoryItemQty() {
		return inventoryItemQty;
	}

	public void setInventoryItemQty(Long inventoryItemQty) {
		this.inventoryItemQty = inventoryItemQty;
	}

	public Long getPriceOfUnit() {
		return priceOfUnit;
	}

	public void setPriceOfUnit(Long priceOfUnit) {
		this.priceOfUnit = priceOfUnit;
	}

	public Boolean getIsAppointInvoice() {
		return isAppointInvoice;
	}

	public void setIsAppointInvoice(Boolean isAppointInvoice) {
		this.isAppointInvoice = isAppointInvoice;
	}

	public Boolean getAutoreverseFlag() {
		return autoreverseFlag;
	}

	public void setAutoreverseFlag(Boolean autoreverseFlag) {
		this.autoreverseFlag = autoreverseFlag;
	}

	public String getReverseTypeCode() {
		return reverseTypeCode;
	}

	public void setReverseTypeCode(String reverseTypeCode) {
		this.reverseTypeCode = reverseTypeCode;
	}

	public String getReverseTypeName() {
		return reverseTypeName;
	}

	public void setReverseTypeName(String reverseTypeName) {
		this.reverseTypeName = reverseTypeName;
	}

	public Date getReversalDate() {
		return reversalDate;
	}

	public void setReversalDate(Date reversalDate) {
		this.reversalDate = reversalDate;
	}

	public String getReversalTrxNumber() {
		return reversalTrxNumber;
	}

	public void setReversalTrxNumber(String reversalTrxNumber) {
		this.reversalTrxNumber = reversalTrxNumber;
	}

	public String getAppointInvoiceOrgName() {
		return appointInvoiceOrgName;
	}

	public void setAppointInvoiceOrgName(String appointInvoiceOrgName) {
		this.appointInvoiceOrgName = appointInvoiceOrgName;
	}

	public String getAppointInvoiceOrgCode() {
		return appointInvoiceOrgCode;
	}

	public void setAppointInvoiceOrgCode(String appointInvoiceOrgCode) {
		this.appointInvoiceOrgCode = appointInvoiceOrgCode;
	}

	public String getAppointInvoiceOrgId() {
		return appointInvoiceOrgId;
	}

	public void setAppointInvoiceOrgId(String appointInvoiceOrgId) {
		this.appointInvoiceOrgId = appointInvoiceOrgId;
	}

	public String getCustomerNumber() {
		return customerNumber;
	}

	public void setCustomerNumber(String customerNumber) {
		this.customerNumber = customerNumber;
	}

	public String getCustGsnRegistrationNumber() {
		return custGsnRegistrationNumber;
	}

	public void setCustGsnRegistrationNumber(String custGsnRegistrationNumber) {
		this.custGsnRegistrationNumber = custGsnRegistrationNumber;
	}

	public String getTrxAffirmSettingId() {
		return trxAffirmSettingId;
	}

	public void setTrxAffirmSettingId(String trxAffirmSettingId) {
		this.trxAffirmSettingId = trxAffirmSettingId;
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public TmsMdTaxTrxType getTmsMdTaxTrxType() {
		return tmsMdTaxTrxType;
	}

	public void setTmsMdTaxTrxType(TmsMdTaxTrxType tmsMdTaxTrxType) {
		this.tmsMdTaxTrxType = tmsMdTaxTrxType;
	}
	

}


