package com.deloitte.tms.base.masterdata.controller;
// Generated by bo.wang with ling2.autoproject

import java.io.Serializable;
import java.util.Collection;
import java.util.Date;
import java.util.Map;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletResponse;

import net.sf.json.JSONArray;
import net.sf.json.JSONObject;
import net.sf.json.JsonConfig;

import org.springframework.stereotype.Component;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.commons.utils.AssertHelper;
import com.deloitte.tms.pl.core.commons.utils.reflect.ReflectUtils;
import com.deloitte.tms.pl.core.commons.utils.PageUtils;
//import com.deloitte.tms.pl.core.commons.springmvc.controller.BaseController;
import com.deloitte.tms.vat.controller.BaseController;
import com.deloitte.tms.vat.core.common.IdGenerator;
import com.deloitte.tms.vat.core.common.JsonDateValueProcessor;
import com.deloitte.tms.base.masterdata.model.TmsMdCurrencyRate;
import com.deloitte.tms.base.masterdata.model.TmsMdCurrencyRateInParam;
import com.deloitte.tms.base.masterdata.service.TmsMdCurrencyRateService;
/**
 * Home object for domain model class TmsMdCurrencyRate.
 * @see com.deloitte.tms.base.masterdata.model
 * @author Hibernate Tools
 */
@Controller
@RequestMapping("tmsMdCurrencyRate")
public class TmsMdCurrencyRateController extends BaseController{
	@Resource
	TmsMdCurrencyRateService tmsMdCurrencyRateService;
	
	@RequestMapping(value = "/initTmsMdCurrencyRate", method = RequestMethod.GET)
	public String initTmsMdCurrencyRate()throws Exception{
		return "vat/tmsmdcurrencyrate/tmsMdCurrencyRate";
	}
	
	@ResponseBody
	@RequestMapping(value = "/loadTmsMdCurrencyRatePage", method = RequestMethod.POST)
	//@RoleAnnotation(roles=RoleDef.ECOMMERCE_ADMIN)
	public void loadTmsMdCurrencyRatePage(@RequestParam Map<String,Object> parameter,HttpServletResponse response) throws Exception {
		DaoPage daoPage=tmsMdCurrencyRateService.findTmsMdCurrencyRateByParams(parameter,PageUtils.getPageNumber(parameter),PageUtils.getPageSize(parameter));
		
		JSONObject result = new JSONObject();
		 JsonConfig jsonConfig = new JsonConfig();  
		 jsonConfig.registerJsonValueProcessor(Date.class, new JsonDateValueProcessor()); 
		 JSONArray jsonArray = JSONArray.fromObject(daoPage.getResult(),jsonConfig);
		result.put("total", daoPage.getRecordCount());
		result.put("rows", jsonArray);// daoPage.getr
		result.put("pages", daoPage.getPageCount());
		result.put("success", true);
		retJson(response, result);
		//return daoPage;
	}
	@ResponseBody
	@RequestMapping(value = "/saveTmsMdCurrencyRate", method = RequestMethod.POST)
	//@RoleAnnotation(roles=RoleDef.ECOMMERCE_ADMIN)
	public void saveTmsMdCurrencyRate(TmsMdCurrencyRateInParam inParam) throws Exception {
		TmsMdCurrencyRate entity=tmsMdCurrencyRateService.convertTmsMdCurrencyRateInParamToEntity(inParam);
		if(AssertHelper.empty(entity.getId())){
			entity.setId(IdGenerator.getUUID());
			tmsMdCurrencyRateService.save(entity);
		}
		else{
			tmsMdCurrencyRateService.update(entity);
		}
		inParam.setId(entity.getId());
	}	
	@ResponseBody
	@RequestMapping(value = "/removeTmsMdCurrencyRates", method = RequestMethod.POST)
	//@RoleAnnotation(roles=RoleDef.ECOMMERCE_ADMIN)
	public void removeTmsMdCurrencyRates(@RequestParam String ids) {
		AssertHelper.notEmpty_assert(ids,"需要删除的用户不能为空");
		String[] tmsMdCurrencyRateIds=ids.split(",");
		//for(String tmsMdCurrencyRateId:tmsMdCurrencyRateIds){
			
		//}
	}
	@ResponseBody
	@RequestMapping(value = "/loadTmsMdCurrencyRate", method = RequestMethod.POST)
	//@RoleAnnotation(roles=RoleDef.ECOMMERCE_ADMIN)
	public Collection<TmsMdCurrencyRateInParam> loadTmsMdCurrencyRate(@RequestParam Map<String, Object> map) throws Exception {
		List result=tmsMdCurrencyRateService.findTmsMdCurrencyRateByParams(map);
		return result;
	}
	@ResponseBody
	@RequestMapping(value = "/loadAddTmsMdCurrencyRate", method = RequestMethod.POST)
	public TmsMdCurrencyRateInParam loadAddTmsMdCurrencyRate(@RequestParam Map<String, Object> map) throws Exception {
		TmsMdCurrencyRateInParam inParam=new TmsMdCurrencyRateInParam();
		return inParam;
	}
	@ResponseBody
	@RequestMapping(value = "/loadModifyTmsMdCurrencyRate", method = RequestMethod.POST)
	public TmsMdCurrencyRateInParam loadModifyTmsMdCurrencyRate(@RequestParam Map<String, Object> map) throws Exception {
		Object id=map.get("id");
		AssertHelper.notEmpty_assert(id,"编辑的主键不能为空");
		TmsMdCurrencyRate entity=(TmsMdCurrencyRate)tmsMdCurrencyRateService.get(TmsMdCurrencyRate.class,id.toString());
		TmsMdCurrencyRateInParam inParam=tmsMdCurrencyRateService.convertTmsMdCurrencyRateToInParam(entity);
		return inParam;
	}
	
	@ResponseBody
	@RequestMapping(value = "/updateModifyTmsMdCurrencyRate", method = RequestMethod.POST)
	public void updateModifyTmsMdCurrencyRate(TmsMdCurrencyRateInParam inParam) throws Exception {
		TmsMdCurrencyRate entity=(TmsMdCurrencyRate)tmsMdCurrencyRateService.get(TmsMdCurrencyRate.class,inParam.getId());
		ReflectUtils.copyProperties(inParam, entity);
		tmsMdCurrencyRateService.update(entity);
	}
}

