package com.deloitte.tms.vat.salesinvoice.dao.impl;
// Generated by bo.wang with ling2.autoproject

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Component;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.commons.utils.AssertHelper;
import com.deloitte.tms.pl.core.dao.impl.BaseDao;
import com.deloitte.tms.vat.salesinvoice.model.InvoiceSendL;
import com.deloitte.tms.vat.salesinvoice.dao.InvoiceSendLDao;
/**
 * Home object for domain model class InvoiceSendL.
 * @see com.deloitte.tms.vat.salesinvoice.model
 * @author Hibernate Tools
 */
@Component(InvoiceSendLDao.BEAN_ID)
public class InvoiceSendLDaoImpl extends BaseDao<InvoiceSendL> implements InvoiceSendLDao{
	public DaoPage findInvoiceSendLByParams(Map params, Integer pageIndex,Integer pageSize)
	{
		StringBuffer query=new StringBuffer();
		Map values=new HashMap();
		buildInvoiceSendLQuery(query, values, params);
		return pageBy(query, values, pageIndex, pageSize);
	}
	public List<InvoiceSendL> findInvoiceSendLByParams(Map params)
	{
		StringBuffer query=new StringBuffer();
		Map values=new HashMap();
		buildInvoiceSendLQuery(query, values, params);
		return findBy(query, values);
	}
	
	public List<InvoiceSendL> findInvoiceSendLByHID(StringBuffer query)
	{
		StringBuffer querys = new StringBuffer();
		Map values=new HashMap();
		querys.append(" from InvoiceSendL where  invoiceDeliveryHId=:invoiceDeliveryHId");
		values.put("invoiceDeliveryHId", query.toString());
		return findBy(querys, values);	
	}
	private void buildInvoiceSendLQuery(StringBuffer query,Map values,Map params) {
		query.append(" from InvoiceSendL where 1=1 ");
		Object value=params.get("status");
		if(value!=null)
		{
			query.append(" and status=:status");
			values.put("status", value);
		}
	}
}

