package com.deloitte.tms.vat.salesinvoice.dao.impl;
// Generated by bo.wang with ling2.autoproject

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Component;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.commons.utils.AssertHelper;
import com.deloitte.tms.pl.core.dao.impl.BaseDao;
import com.deloitte.tms.vat.salesinvoice.model.TmsCrvatInvReqBatchesL;
import com.deloitte.tms.vat.salesinvoice.dao.TmsCrvatInvReqBatchesLDao;
/**
 * Home object for domain model class TmsCrvatInvReqBatchesL.
 * @see com.deloitte.tms.vat.salesinvoice.model
 * @author Hibernate Tools
 */
@Component(TmsCrvatInvReqBatchesLDao.BEAN_ID)
public class TmsCrvatInvReqBatchesLDaoImpl extends BaseDao<TmsCrvatInvReqBatchesL> implements TmsCrvatInvReqBatchesLDao{
	public DaoPage findTmsCrvatInvReqBatchesLByParams(Map params, Integer pageIndex,Integer pageSize)
	{
		StringBuffer query=new StringBuffer();
		Map values=new HashMap();
		buildTmsCrvatInvReqBatchesLQuery(query, values, params);
		return pageBy(query, values, pageIndex, pageSize);
	}
	public List<TmsCrvatInvReqBatchesL> findTmsCrvatInvReqBatchesLByParams(Map params)
	{
		StringBuffer query=new StringBuffer();
		Map values=new HashMap();
		buildTmsCrvatInvReqBatchesLQuery(query, values, params);
		return findBy(query, values);
	}
	private void buildTmsCrvatInvReqBatchesLQuery(StringBuffer query,Map values,Map params) {
		query.append(" from TmsCrvatInvReqBatchesL where 1=1 ");
		Object value=params.get("status");
		if(value!=null)
		{
			query.append(" and status=:status");
			values.put("status", value);
		}
	}
}

