package com.deloitte.tms.vat.purchinvoice.dao.impl;
// Generated by bo.wang with ling2.autoproject

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Component;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.commons.utils.AssertHelper;
import com.deloitte.tms.pl.core.dao.impl.BaseDao;
import com.deloitte.tms.vat.purchinvoice.model.TmsDrvatInvoiceOnhand;
import com.deloitte.tms.vat.purchinvoice.dao.TmsDrvatInvoiceOnhandDao;
/**
 * Home object for domain model class TmsDrvatInvoiceOnhand.
 * @see com.deloitte.tms.vat.purchinvoice.model
 * @author Hibernate Tools
 */
@Component(TmsDrvatInvoiceOnhandDao.BEAN_ID)
public class TmsDrvatInvoiceOnhandDaoImpl extends BaseDao<TmsDrvatInvoiceOnhand> implements TmsDrvatInvoiceOnhandDao{
	public DaoPage findTmsDrvatInvoiceOnhandByParams(Map params, Integer pageIndex,Integer pageSize)
	{
		StringBuffer query=new StringBuffer();
		Map values=new HashMap();
		buildTmsDrvatInvoiceOnhandQuery(query, values, params);
		return pageBy(query, values, pageIndex, pageSize);
	}
	public List<TmsDrvatInvoiceOnhand> findTmsDrvatInvoiceOnhandByParams(Map params)
	{
		StringBuffer query=new StringBuffer();
		Map values=new HashMap();
		buildTmsDrvatInvoiceOnhandQuery(query, values, params);
		return findBy(query, values);
	}
	private void buildTmsDrvatInvoiceOnhandQuery(StringBuffer query,Map values,Map params) {
		//query.append(" from TmsDrvatInvoiceOnhand where flag!=1 ");
		query.append(" from ").append(TmsDrvatInvoiceOnhand.class.getName() ).append( " where flag!=1 ");
		Object value=params.get("status");
		if(value!=null)
		{
			query.append(" and status=:status");
			values.put("status", value);
		}
	}
}

