package com.deloitte.tms.vat.salesinvoice.jobs.model;


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.deloitte.tms.pl.core.commons.annotation.ModelProperty;
import com.deloitte.tms.pl.core.hibernate.identifier.Ling2UUIDGenerator;
import com.deloitte.tms.pl.core.model.impl.BaseEntity;

/**
 * TmsCrvatInvReqBatInf generated by ling autoproject
 */
@Entity
@Table(name=TmsCrvatInvReqBatInf.TABLE)
public class TmsCrvatInvReqBatInf extends BaseEntity {

	public static final String TABLE = "TMS_CRVAT_INV_REQ_BAT_INF";
	public static final String SEQ = TABLE;

    @Id
	@GenericGenerator(name=SEQ+"_GENERATOR",strategy=Ling2UUIDGenerator.STRATEGY_NAME,parameters={@Parameter(name="pkColumnValue",value=SEQ)})
	@GeneratedValue(strategy = GenerationType.TABLE, generator = SEQ+"_GENERATOR")

    @Column(name="INTERFACE_TRX_ID", length=36)
	@ModelProperty(comment="接口处理ID")
	private String id;
    
    @Column(name="INTERFACE_TRX_DATE", length=7)
	@ModelProperty(comment="接口处理日期")
	private Date interfaceTrxDate;

    @Column(name="INTERFACE_TRX_FLAG", length=10)
	@ModelProperty(comment="接口处理标记")
	private String interfaceTrxFlag;

    @Column(name="INTERFACE_TRX_MSG", length=2000)
	@ModelProperty(comment="接口处理信息")
	private String interfaceTrxMsg;

    @Column(name="REQUEST_ID", length=36)
	@ModelProperty(comment="接口处理处理请求ID(自动任务ID)")
	private String requestId;

    @Column(name="CRVAT_INVOICE_REQ_NUMBER", length=100)
	@ModelProperty(comment="特殊批量开票申请单号")
	private String crvatInvoiceReqNumber;

    @Column(name="ORG_ID", length=36)
	@ModelProperty(comment="组织ID")
	private String orgId;

    @Column(name="SOURCE_ORG_ID", length=100)
	@ModelProperty(comment="来源组织ID")
	private String sourceOrgId;

    @Column(name="SOURCE_ORG_CODE", length=100)
	@ModelProperty(comment="来源组织CODE")
	private String sourceOrgCode;

    @Column(name="SOURCE_INVOICE_REQ_BY", length=7)
	@ModelProperty(comment="来原申请人")
	private String sourceInvoiceReqBy;

    public String getSourceInvoiceReqBy() {
		return sourceInvoiceReqBy;
	}

	public void setSourceInvoiceReqBy(String sourceInvoiceReqBy) {
		this.sourceInvoiceReqBy = sourceInvoiceReqBy;
	}

	@Column(name="INVOICE_REQ_DATE", length=7)
	@ModelProperty(comment="申请日期")
	private Date invoiceReqDate;

    @Column(name="REQ_DEPT_NO", length=100)
	@ModelProperty(comment="申请部门")
	private String reqDeptNo;

    @Column(name="SOURCE_REQ_DEPT_NO", length=100)
	@ModelProperty(comment="来源申请部门")
	private String sourceReqDeptNo;

    @Column(name="INVOICE_REQ_TYPE", length=100)
	@ModelProperty(comment="申请开票类型(柜台/特殊/自动匹配/特殊批量)_预留")
	private String invoiceReqType;

    @Column(name="LEGAL_ENTITY_ID", length=36)
	@ModelProperty(comment="销方纳税人实体ID")
	private String legalEntityId;

    @Column(name="SOURCE_LEGAL_ENTITY_ID", length=100)
	@ModelProperty(comment="来源销方纳税人ID")
	private String sourceLegalEntityId;

    @Column(name="SOURCE_LEGAL_ENTITY_CODE", length=100)
	@ModelProperty(comment="来源销方纳税人代码")
	private String sourceLegalEntityCode;

    @Column(name="PRT_LEGAL_ENTITY_ID", length=36)
	@ModelProperty(comment="打印点法人实体ID")
	private String prtLegalEntityId;

    @Column(name="SOURCE_PRT_LEGAL_ENTITY_ID", length=100)
	@ModelProperty(comment="来源打印点法人实体ID")
	private String sourcePrtLegalEntityId;

    @Column(name="SOURCE_PRT_LEGAL_ENTITY_CODE", length=100)
	@ModelProperty(comment="来源打印点法人实体代码")
	private String sourcePrtLegalEntityCode;

    @Column(name="EQUIPMENT_ID", length=36)
	@ModelProperty(comment="终端设备ID")
	private String equipmentId;

    @Column(name="SOURCE_EQUIPMENT_ID", length=100)
	@ModelProperty(comment="来源终端设备ID")
	private String sourceEquipmentId;

    @Column(name="SOURCE_EQUIPMENT_CODE", length=100)
	@ModelProperty(comment="来源终端设备代码")
	private String sourceEquipmentCode;

    @Column(name="INVOICING_TYPE", length=100)
	@ModelProperty(comment="开票方式_枚举值(明细/汇总)")
	private String invoicingType;

    @Column(name="REQ_INVOICE_RANGE", length=100)
	@ModelProperty(comment="发票打印受理层级范围_枚举值")
	private String reqInvoiceRange;

    @Column(name="IS_RECEIPTS", length=10)
	@ModelProperty(comment="是否已收款")
	private String isReceipts;

    @Column(name="BUSINESS_CATEGORIES", length=100)
	@ModelProperty(comment="业务大类_枚举值")
	private String businessCategories;

    @Column(name="DELIVERY_TYPE", length=100)
	@ModelProperty(comment="寄送类型_枚举值(内部/外包)")
	private String deliveryType;

    @Column(name="CUSTOMER_ID", length=36)
	@ModelProperty(comment="购方名称ID")
	private String customerId;

    @Column(name="SOURCE_CUSTOMER_ID", length=100)
	@ModelProperty(comment="来源购方ID")
	private String sourceCustomerId;

    @Column(name="SOURCE_CUSTOMER_NUMBER", length=100)
	@ModelProperty(comment="来源购方代码")
	private String sourceCustomerNumber;

    @Column(name="SOURCE_CUSTOMER_ACC_NUM", length=100)
	@ModelProperty(comment="来源购方资金账号代码")
	private String sourceCustomerAccNum;

    @Column(name="PROJECT_ID", length=36)
	@ModelProperty(comment="项目ID")
	private String projectId;

    @Column(name="SOURCE_PROJECT_NUMBER", length=100)
	@ModelProperty(comment="来源项目编码")
	private String sourceProjectNumber;

    @Column(name="CONTRACT_ID", length=36)
	@ModelProperty(comment="合同ID(冗余)")
	private String contractId;

    @Column(name="SOURCE_CONTRACT_NUMBER", length=100)
	@ModelProperty(comment="来源合同编码")
	private String sourceContractNumber;

    @Column(name="INVENTORY_ITEM_QTY")
	@ModelProperty(comment="数量")
	private Long inventoryItemQty;

    @Column(name="TRX_AFFIRM_SETTING_ID", length=36)
	@ModelProperty(comment="涉税交易认定设置规则ID")
	private String trxAffirmSettingId;

    @Column(name="TAX_TRX_TYPE_ID", length=36)
	@ModelProperty(comment="涉税交易类型ID")
	private String taxTrxTypeId;

    @Column(name="SOURCE_TAX_TYPE_CODE", length=100)
	@ModelProperty(comment="涉税交易类型代码")
	private String sourceTaxTypeCode;

    @Column(name="SOURCE_TAX_TYPE_NAME", length=100)
	@ModelProperty(comment="涉税交易类型名称")
	private String sourceTaxTypeName;

    @Column(name="INVOICE_AMOUNT")
	@ModelProperty(comment="本次开票总金额")
	private Long invoiceAmount;

    @Column(name="TAX_RATE")
	@ModelProperty(comment="税率")
	private Long taxRate;

    @Column(name="SOURCE_APPROVAL_BY", length=36)
	@ModelProperty(comment="最后审批人")
	private String sourceApprovalBy;

    @Column(name="APPROVAL_DATE", length=7)
	@ModelProperty(comment="最后审批日期")
	private Date approvalDate;

    @Column(name="APPROVAL_STATUS", length=100)
	@ModelProperty(comment="审批状态")
	private String approvalStatus;

    @Column(name="APPROVAL_DESC", length=500)
	@ModelProperty(comment="审批流状态描述")
	private String approvalDesc;

    @Column(name="SOURCE_WF_TASK_ID", length=36)
	@ModelProperty(comment="来源工作流ID")
	private String sourceWfTaskId;

    @Column(name="SOURCE_WF_TASK_NUMBER", length=100)
	@ModelProperty(comment="来源工作编码")
	private String sourceWfTaskNumber;

    @Column(name="IS_TAX", length=10)
	@ModelProperty(comment="是否含税")
	private String isTax;

    @Column(name="SOURCE_CODE", length=100)
	@ModelProperty(comment="来源系统")
	private String sourceCode;

    @Column(name="SOURCE_BATCH_NUMBER", length=100)
	@ModelProperty(comment="来源特殊批量开票申请批号")
	private String sourceBatchNumber;

    @Column(name="SOURCE_CRVAT_INV_REQ_BAT_ID", length=100)
	@ModelProperty(comment="来源特殊批量开票申请ID")
	private String sourceCrvatInvReqBatId;

    @Column(name="START_DATE", length=7)
	@ModelProperty(comment="有效日期")
	private Date startDate;

    @Column(name="END_DATE", length=7)
	@ModelProperty(comment="失效日期")
	private Date endDate;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getInterfaceTrxDate() {
		return interfaceTrxDate;
	}

	public void setInterfaceTrxDate(Date interfaceTrxDate) {
		this.interfaceTrxDate = interfaceTrxDate;
	}

	public String getInterfaceTrxFlag() {
		return interfaceTrxFlag;
	}

	public void setInterfaceTrxFlag(String interfaceTrxFlag) {
		this.interfaceTrxFlag = interfaceTrxFlag;
	}

	public String getInterfaceTrxMsg() {
		return interfaceTrxMsg;
	}

	public void setInterfaceTrxMsg(String interfaceTrxMsg) {
		this.interfaceTrxMsg = interfaceTrxMsg;
	}

	public String getRequestId() {
		return requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	public String getCrvatInvoiceReqNumber() {
		return crvatInvoiceReqNumber;
	}

	public void setCrvatInvoiceReqNumber(String crvatInvoiceReqNumber) {
		this.crvatInvoiceReqNumber = crvatInvoiceReqNumber;
	}

	public String getOrgId() {
		return orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	public String getSourceOrgId() {
		return sourceOrgId;
	}

	public void setSourceOrgId(String sourceOrgId) {
		this.sourceOrgId = sourceOrgId;
	}

	public String getSourceOrgCode() {
		return sourceOrgCode;
	}

	public void setSourceOrgCode(String sourceOrgCode) {
		this.sourceOrgCode = sourceOrgCode;
	}


	public Date getInvoiceReqDate() {
		return invoiceReqDate;
	}

	public void setInvoiceReqDate(Date invoiceReqDate) {
		this.invoiceReqDate = invoiceReqDate;
	}

	public String getReqDeptNo() {
		return reqDeptNo;
	}

	public void setReqDeptNo(String reqDeptNo) {
		this.reqDeptNo = reqDeptNo;
	}

	public String getSourceReqDeptNo() {
		return sourceReqDeptNo;
	}

	public void setSourceReqDeptNo(String sourceReqDeptNo) {
		this.sourceReqDeptNo = sourceReqDeptNo;
	}

	public String getInvoiceReqType() {
		return invoiceReqType;
	}

	public void setInvoiceReqType(String invoiceReqType) {
		this.invoiceReqType = invoiceReqType;
	}

	public String getLegalEntityId() {
		return legalEntityId;
	}

	public void setLegalEntityId(String legalEntityId) {
		this.legalEntityId = legalEntityId;
	}

	public String getSourceLegalEntityId() {
		return sourceLegalEntityId;
	}

	public void setSourceLegalEntityId(String sourceLegalEntityId) {
		this.sourceLegalEntityId = sourceLegalEntityId;
	}

	public String getSourceLegalEntityCode() {
		return sourceLegalEntityCode;
	}

	public void setSourceLegalEntityCode(String sourceLegalEntityCode) {
		this.sourceLegalEntityCode = sourceLegalEntityCode;
	}

	public String getPrtLegalEntityId() {
		return prtLegalEntityId;
	}

	public void setPrtLegalEntityId(String prtLegalEntityId) {
		this.prtLegalEntityId = prtLegalEntityId;
	}

	public String getSourcePrtLegalEntityId() {
		return sourcePrtLegalEntityId;
	}

	public void setSourcePrtLegalEntityId(String sourcePrtLegalEntityId) {
		this.sourcePrtLegalEntityId = sourcePrtLegalEntityId;
	}

	public String getSourcePrtLegalEntityCode() {
		return sourcePrtLegalEntityCode;
	}

	public void setSourcePrtLegalEntityCode(String sourcePrtLegalEntityCode) {
		this.sourcePrtLegalEntityCode = sourcePrtLegalEntityCode;
	}

	public String getEquipmentId() {
		return equipmentId;
	}

	public void setEquipmentId(String equipmentId) {
		this.equipmentId = equipmentId;
	}

	public String getSourceEquipmentId() {
		return sourceEquipmentId;
	}

	public void setSourceEquipmentId(String sourceEquipmentId) {
		this.sourceEquipmentId = sourceEquipmentId;
	}

	public String getSourceEquipmentCode() {
		return sourceEquipmentCode;
	}

	public void setSourceEquipmentCode(String sourceEquipmentCode) {
		this.sourceEquipmentCode = sourceEquipmentCode;
	}

	public String getInvoicingType() {
		return invoicingType;
	}

	public void setInvoicingType(String invoicingType) {
		this.invoicingType = invoicingType;
	}

	public String getReqInvoiceRange() {
		return reqInvoiceRange;
	}

	public void setReqInvoiceRange(String reqInvoiceRange) {
		this.reqInvoiceRange = reqInvoiceRange;
	}

	public String getIsReceipts() {
		return isReceipts;
	}

	public void setIsReceipts(String isReceipts) {
		this.isReceipts = isReceipts;
	}

	public String getBusinessCategories() {
		return businessCategories;
	}

	public void setBusinessCategories(String businessCategories) {
		this.businessCategories = businessCategories;
	}

	public String getDeliveryType() {
		return deliveryType;
	}

	public void setDeliveryType(String deliveryType) {
		this.deliveryType = deliveryType;
	}

	public String getCustomerId() {
		return customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public String getSourceCustomerId() {
		return sourceCustomerId;
	}

	public void setSourceCustomerId(String sourceCustomerId) {
		this.sourceCustomerId = sourceCustomerId;
	}

	public String getSourceCustomerNumber() {
		return sourceCustomerNumber;
	}

	public void setSourceCustomerNumber(String sourceCustomerNumber) {
		this.sourceCustomerNumber = sourceCustomerNumber;
	}

	public String getSourceCustomerAccNum() {
		return sourceCustomerAccNum;
	}

	public void setSourceCustomerAccNum(String sourceCustomerAccNum) {
		this.sourceCustomerAccNum = sourceCustomerAccNum;
	}

	public String getProjectId() {
		return projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	public String getSourceProjectNumber() {
		return sourceProjectNumber;
	}

	public void setSourceProjectNumber(String sourceProjectNumber) {
		this.sourceProjectNumber = sourceProjectNumber;
	}

	public String getContractId() {
		return contractId;
	}

	public void setContractId(String contractId) {
		this.contractId = contractId;
	}

	public String getSourceContractNumber() {
		return sourceContractNumber;
	}

	public void setSourceContractNumber(String sourceContractNumber) {
		this.sourceContractNumber = sourceContractNumber;
	}

	public Long getInventoryItemQty() {
		return inventoryItemQty;
	}

	public void setInventoryItemQty(Long inventoryItemQty) {
		this.inventoryItemQty = inventoryItemQty;
	}

	public String getTrxAffirmSettingId() {
		return trxAffirmSettingId;
	}

	public void setTrxAffirmSettingId(String trxAffirmSettingId) {
		this.trxAffirmSettingId = trxAffirmSettingId;
	}

	public String getTaxTrxTypeId() {
		return taxTrxTypeId;
	}

	public void setTaxTrxTypeId(String taxTrxTypeId) {
		this.taxTrxTypeId = taxTrxTypeId;
	}

	public String getSourceTaxTypeCode() {
		return sourceTaxTypeCode;
	}

	public void setSourceTaxTypeCode(String sourceTaxTypeCode) {
		this.sourceTaxTypeCode = sourceTaxTypeCode;
	}

	public String getSourceTaxTypeName() {
		return sourceTaxTypeName;
	}

	public void setSourceTaxTypeName(String sourceTaxTypeName) {
		this.sourceTaxTypeName = sourceTaxTypeName;
	}

	public Long getInvoiceAmount() {
		return invoiceAmount;
	}

	public void setInvoiceAmount(Long invoiceAmount) {
		this.invoiceAmount = invoiceAmount;
	}

	public Long getTaxRate() {
		return taxRate;
	}

	public void setTaxRate(Long taxRate) {
		this.taxRate = taxRate;
	}

	public String getSourceApprovalBy() {
		return sourceApprovalBy;
	}

	public void setSourceApprovalBy(String sourceApprovalBy) {
		this.sourceApprovalBy = sourceApprovalBy;
	}

	public Date getApprovalDate() {
		return approvalDate;
	}

	public void setApprovalDate(Date approvalDate) {
		this.approvalDate = approvalDate;
	}

	public String getApprovalStatus() {
		return approvalStatus;
	}

	public void setApprovalStatus(String approvalStatus) {
		this.approvalStatus = approvalStatus;
	}

	public String getApprovalDesc() {
		return approvalDesc;
	}

	public void setApprovalDesc(String approvalDesc) {
		this.approvalDesc = approvalDesc;
	}

	public String getSourceWfTaskId() {
		return sourceWfTaskId;
	}

	public void setSourceWfTaskId(String sourceWfTaskId) {
		this.sourceWfTaskId = sourceWfTaskId;
	}

	public String getSourceWfTaskNumber() {
		return sourceWfTaskNumber;
	}

	public void setSourceWfTaskNumber(String sourceWfTaskNumber) {
		this.sourceWfTaskNumber = sourceWfTaskNumber;
	}

	public String getIsTax() {
		return isTax;
	}

	public void setIsTax(String isTax) {
		this.isTax = isTax;
	}

	public String getSourceCode() {
		return sourceCode;
	}

	public void setSourceCode(String sourceCode) {
		this.sourceCode = sourceCode;
	}

	public String getSourceBatchNumber() {
		return sourceBatchNumber;
	}

	public void setSourceBatchNumber(String sourceBatchNumber) {
		this.sourceBatchNumber = sourceBatchNumber;
	}

	public String getSourceCrvatInvReqBatId() {
		return sourceCrvatInvReqBatId;
	}

	public void setSourceCrvatInvReqBatId(String sourceCrvatInvReqBatId) {
		this.sourceCrvatInvReqBatId = sourceCrvatInvReqBatId;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

   
}


