package com.deloitte.tms.base.taxsetting.dao;
// Generated by bo.wang with ling2.autoproject

import java.util.List;
import java.util.Map;

import com.deloitte.tms.base.taxsetting.model.TaxCategory;
import com.deloitte.tms.base.taxsetting.model.Items;
import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.dao.IDao;
/**
 * Home object for domain model class TaxCategory.
 * @see com.deloitte.tms.base.taxsetting.model
 * @author Hibernate Tools
 */
public interface TaxCategoryDao extends IDao<TaxCategory>{
	public static final String BEAN_ID="taxCategoryDao";
	public DaoPage findTaxCategoryByParams(Map params, Integer pageIndex,Integer pageSize);
	public List<TaxCategory> findTaxCategoryByParams(Map params);
	public DaoPage findItemsByParams(Map params, Integer pageIndex,Integer pageSize);
	public List<Items> findItemsByParams(Map params);
	/**
	 * @author sqing
	 */
	public String findTaxCategoryNameById(String categoryId);
	
	public List findBySearchTax(String hql);
}

