package com.deloitte.tms.base.taxsetting.dao;
// Generated by bo.wang with ling2.autoproject

import java.util.List;
import java.util.Map;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.dao.IDao;
import com.deloitte.tms.base.taxsetting.model.TmsMdTrxAffirmSetting;
/**
 * Home object for domain model class TmsMdTrxAffirmSetting.
 * @see com.deloitte.tms.base.masterdata.model
 * @author Hibernate Tools
 */
public interface TmsMdTrxAffirmSettingDao extends IDao<TmsMdTrxAffirmSetting>{
	public static final String BEAN_ID="tmsMdTrxAffirmSettingDao";
	public DaoPage findTmsMdTrxAffirmSettingByParams(Map params, Integer pageIndex,Integer pageSize);
	public List<TmsMdTrxAffirmSetting> findTmsMdTrxAffirmSettingByParams(Map params);
}

