package com.deloitte.tms.base.taxsetting.dao;
// Generated by bo.wang with ling2.autoproject

import java.util.List;
import java.util.Map;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.dao.IDao;
import com.deloitte.tms.base.taxsetting.model.TmsMdOrgParameter;
/**
 * Home object for domain model class TmsMdOrgParameter.
 * @see com.deloitte.tms.base.masterdata.model
 * @author Hibernate Tools
 */
public interface TmsMdOrgParameterDao extends IDao<TmsMdOrgParameter>{
	public static final String BEAN_ID="tmsMdOrgParameterDao";
	public DaoPage findTmsMdOrgParameterByParams(Map params, Integer pageIndex,Integer pageSize);
	public List<TmsMdOrgParameter> findTmsMdOrgParameterByParams(Map params);
}

