package com.deloitte.tms.base.taxsetting.dao;
// Generated by bo.wang with ling2.autoproject

import java.util.List;
import java.util.Map;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.dao.IDao;
import com.deloitte.tms.base.taxsetting.model.TmsMdOrgBsnStructures;
/**
 * Home object for domain model class TmsMdOrgBsnStructures.
 * @see com.deloitte.tms.base.masterdata.model
 * @author Hibernate Tools
 */
public interface TmsMdOrgBsnStructuresDao extends IDao<TmsMdOrgBsnStructures>{
	public static final String BEAN_ID="tmsMdOrgBsnStructuresDao";
	public DaoPage findTmsMdOrgBsnStructuresByParams(Map params, Integer pageIndex,Integer pageSize);
	public List<TmsMdOrgBsnStructures> findTmsMdOrgBsnStructuresByParams(Map params);
}

