package com.deloitte.tms.base.taxsetting.service;
// Generated by bo.wang with ling2.autoproject

import java.util.List;
import java.util.Map;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.service.IService;
import com.deloitte.tms.base.taxsetting.dao.TmsMdInventoryCategoriesDao;
import com.deloitte.tms.base.taxsetting.model.TmsMdInventoryCategories;
import com.deloitte.tms.base.taxsetting.model.TmsMdInventoryCategoriesInParam;
import com.deloitte.tms.base.taxsetting.model.TmsMdInventoryItems;
import com.deloitte.tms.base.taxsetting.model.TmsMdInventoryItemsInParam;
/**
 * Home object for domain model class TmsMdInventoryCategories.
 * @see com.deloitte.tms.base.masterdata.model
 * @author Hibernate Tools
 */
public interface TmsMdInventoryCategoriesService extends IService{
	public static final String BEAN_ID="tmsMdInventoryCategoriesService";
	
	public DaoPage findTmsMdInventoryCategoriesByParams(Map params, Integer pageIndex,Integer pageSize);
	
	public List<TmsMdInventoryCategoriesInParam> findTmsMdInventoryCategoriesByParams(Map params);
	
	public void saveTmsMdInventoryCategoriesDataListsMap(Map dataListsMap);
	
	public TmsMdInventoryCategoriesInParam convertTmsMdInventoryCategoriesToInParam(TmsMdInventoryCategories model);
	
	public TmsMdInventoryCategories convertTmsMdInventoryCategoriesInParamToEntity(TmsMdInventoryCategoriesInParam inParam);
	
	public DaoPage findTmsMdInventoryItemsByParams(Map params, Integer pageIndex,Integer pageSize);
	
	public List<TmsMdInventoryItemsInParam> findTmsMdInventoryItemsByParams(Map params);
	
	public void saveTmsMdInventoryItemsDataListsMap(Map dataListsMap);
	
	public TmsMdInventoryItemsInParam convertTmsMdInventoryItemsToInParam(TmsMdInventoryItems model);
	
	public TmsMdInventoryItems convertTmsMdInventoryItemsInParamToEntity(TmsMdInventoryItemsInParam inParam);
	
}

