package com.deloitte.tms.vat.purchinvoice.service;
// Generated by bo.wang with ling2.autoproject

import java.util.List;
import java.util.Map;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.service.IService;
import com.deloitte.tms.vat.purchinvoice.model.TmsDrvatInvoiceOnhand;
import com.deloitte.tms.vat.purchinvoice.model.TmsDrvatInvoiceOnhandInParam;
import com.deloitte.tms.vat.purchinvoice.dao.TmsDrvatInvoiceOnhandDao;
/**
 * Home object for domain model class TmsDrvatInvoiceOnhand.
 * @see com.deloitte.tms.vat.purchinvoice.model
 * @author Hibernate Tools
 */
public interface TmsDrvatInvoiceOnhandService extends IService{
	public static final String BEAN_ID="tmsDrvatInvoiceOnhandService";
	
	public DaoPage findTmsDrvatInvoiceOnhandByParams(Map params, Integer pageIndex,Integer pageSize);
	
	public List<TmsDrvatInvoiceOnhandInParam> findTmsDrvatInvoiceOnhandByParams(Map params);
	
	public void saveTmsDrvatInvoiceOnhandDataListsMap(Map dataListsMap);
	
	public TmsDrvatInvoiceOnhandInParam convertTmsDrvatInvoiceOnhandToInParam(TmsDrvatInvoiceOnhand model);
	
	public TmsDrvatInvoiceOnhand convertTmsDrvatInvoiceOnhandInParamToEntity(TmsDrvatInvoiceOnhandInParam inParam);
	
}

