package com.deloitte.tms.vat.bill.pm.dao.impl;
// Generated by bo.wang with ling2.autoproject

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Component;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.commons.utils.AssertHelper;
import com.deloitte.tms.pl.core.dao.impl.BaseDao;
import com.deloitte.tms.vat.bill.pm.model.BillBook;
import com.deloitte.tms.vat.bill.pm.dao.BillBookDao;
/**
 * Home object for domain model class BillBook.
 * @see com.deloitte.tms.vat.bill.pm.model
 * @author Hibernate Tools
 */
@Component(BillBookDao.BEAN_ID)
public class BillBookDaoImpl extends BaseDao<BillBook> implements BillBookDao{
	public DaoPage findBillBookByParams(Map params, Integer pageIndex,Integer pageSize)
	{
		StringBuffer query=new StringBuffer();
		Map values=new HashMap();
		buildBillBookQuery(query, values, params);
		return pageBy(query, values, pageIndex, pageSize);
	}
	public List<BillBook> findBillBookByParams(Map params)
	{
		StringBuffer query=new StringBuffer();
		Map values=new HashMap();
		buildBillBookQuery(query, values, params);
		return findBy(query, values);
	}
	private void buildBillBookQuery(StringBuffer query,Map values,Map params) {
		query.append(" from BillBook where 1=1 ");
		Object value=params.get("status");
		if(value!=null)
		{
			query.append(" and status=:status");
			values.put("status", value);
		}
	}
}

