package com.deloitte.tms.base.masterdata.service.impl;
// Generated by bo.wang with ling2.autoproject

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

import javax.annotation.Resource;

import org.springframework.stereotype.Component;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.commons.utils.AssertHelper;
import com.deloitte.tms.pl.core.commons.utils.BatchUtils;
import com.deloitte.tms.pl.core.commons.utils.reflect.ReflectUtils;
import com.deloitte.tms.pl.core.dao.IDao;
import com.deloitte.tms.pl.core.service.impl.BaseService;
import com.deloitte.tms.base.masterdata.model.BaseOrg;
import com.deloitte.tms.base.masterdata.model.BaseOrgInParam;
import com.deloitte.tms.base.masterdata.model.BaseOrg;
import com.deloitte.tms.base.masterdata.model.BaseOrgInParam;
import com.deloitte.tms.base.masterdata.dao.BaseOrgDao;
import com.deloitte.tms.base.masterdata.service.BaseOrgService;
import com.deloitte.tms.base.taxsetting.model.TmsMdTrxCatBsnStr;
/**
 * Home object for domain model class BaseOrg.
 * @see com.deloitte.tms.base.masterdata.model
 * @author Hibernate Tools
 */
@Component(BaseOrgService.BEAN_ID)
public class BaseOrgServiceImpl extends BaseService implements BaseOrgService{

	@Resource
	private BaseOrgDao baseOrgDao;
	
	/**   
	 * @return  
	 * @see com.deloitte.tms.pl.core.service.IService#getDao()  
	 */
	
	@Override
	public IDao getDao() {
		// TODO Auto-generated method stub
		return null;
	}

	
	/**   
	 * @param params
	 * @param pageIndex
	 * @param pageSize
	 * @return  
	 * @see com.deloitte.tms.base.masterdata.service.BaseOrgService#findBaseOrgByParams(java.util.Map, java.lang.Integer, java.lang.Integer)  
	 */
	
	@Override
	public DaoPage findBaseOrgByParams(Map params, Integer pageIndex,
			Integer pageSize) {
		if(params==null)
		{
			params=new HashMap();
		}			
		return baseOrgDao.findBaseOrgByParams(params, pageIndex, pageSize);
	}

	
	/**   
	 * @param params
	 * @return  
	 * @see com.deloitte.tms.base.masterdata.service.BaseOrgService#findBaseOrgByParams(java.util.Map)  
	 */
	
	@Override
	public List<BaseOrgInParam> findBaseOrgByParams(Map params) {
		// TODO Auto-generated method stub
		return null;
	}

	
	/**   
	 * @param dataListsMap  
	 * @see com.deloitte.tms.base.masterdata.service.BaseOrgService#saveBaseOrgDataListsMap(java.util.Map)  
	 */
	
	@Override
	public void saveBaseOrgDataListsMap(Map dataListsMap) {
		// TODO Auto-generated method stub
		
	}

	
	/**   
	 * @param model
	 * @return  
	 * @see com.deloitte.tms.base.masterdata.service.BaseOrgService#convertBaseOrgToInParam(com.deloitte.tms.base.masterdata.model.BaseOrg)  
	 */
	
	@Override
	public BaseOrgInParam convertBaseOrgToInParam(BaseOrg model) {
		// TODO Auto-generated method stub
		return null;
	}

	
	/**   
	 * @param inParam
	 * @return  
	 * @see com.deloitte.tms.base.masterdata.service.BaseOrgService#convertBaseOrgInParamToEntity(com.deloitte.tms.base.masterdata.model.BaseOrgInParam)  
	 */
	
	@Override
	public BaseOrg convertBaseOrgInParamToEntity(BaseOrgInParam inParam) {
		// TODO Auto-generated method stub
		return null;
	}


	
	/**   
	 * @param orgCode
	 * @return  
	 * @see com.deloitte.tms.base.masterdata.service.BaseOrgService#findBaseOrgByOrgCode(java.lang.String)  
	 */
	
	@Override
	public BaseOrg findBaseOrgByOrgCode(String orgCode) {
		return baseOrgDao.findBaseOrgByCode(orgCode);
		
	}
	
}

