package com.deloitte.tms.base.masterdata.dao.impl;
// Generated by bo.wang with ling2.autoproject

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Component;

import com.deloitte.tms.base.masterdata.dao.ClientDao;
import com.deloitte.tms.base.masterdata.model.Client;
import com.deloitte.tms.base.masterdata.model.ClientSec;
import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.dao.impl.BaseDao;
/**
 * Home object for domain model class Client.
 * @see com.deloitte.tms.base.masterdata.model
 * @author Hibernate Tools
 */
@Component(ClientDao.BEAN_ID)
public class ClientDaoImpl extends BaseDao<Client> implements ClientDao{
	public DaoPage findClientByParams(Map params, Integer pageIndex,Integer pageSize)
	{
		StringBuffer query=new StringBuffer();
		Map values=new HashMap();
		buildClientQuery(query, values, params);
		return pageBy(query, values, pageIndex, pageSize);
	}
	public List<Client> findClientByParams(Map params)
	{
		StringBuffer query=new StringBuffer();
		Map values=new HashMap();
		buildClientQuery(query, values, params);
		return findBy(query, values);
	}
	private void buildClientQuery(StringBuffer query,Map values,Map params) {
		query.append(" from Client where 1=1 ");
		Object value=params.get("status");
		if(value!=null)
		{
			query.append(" and status=:status");
			values.put("status", value);
		}
	}
	public DaoPage findClientSecByParams(Map params, Integer pageIndex,Integer pageSize)
	{
		StringBuffer query=new StringBuffer();
		Map values=new HashMap();
		buildClientSecQuery(query, values, params);
		return pageBy(query, values, pageIndex, pageSize);
	}
	public List<ClientSec> findClientSecByParams(Map params)
	{
		StringBuffer query=new StringBuffer();
		Map values=new HashMap();
		buildClientSecQuery(query, values, params);
		return findBy(query, values);
	}
	private void buildClientSecQuery(StringBuffer query,Map values,Map params) {
		query.append(" from ClientSec where 1=1 ");
		Object value=params.get("clientId");
		if(value!=null&&!"".equals(value))
		{
			value=Long.parseLong(value.toString());
			query.append(" and clientId=:clientId");
			values.put("clientId", value);
		}
		value=params.get("status");
		if(value!=null)
		{
			query.append(" and status=:status");
			values.put("status", value);
		}
	}
}

