package com.deloitte.tms.base.masterdata.dao.impl;
// Generated by bo.wang with ling2.autoproject

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Component;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.commons.utils.AssertHelper;
import com.deloitte.tms.pl.core.dao.impl.BaseDao;
import com.deloitte.tms.base.masterdata.model.CustBankAccount;
import com.deloitte.tms.base.masterdata.dao.CustBankAccountDao;
/**
 * Home object for domain model class CustBankAccount.
 * @see com.deloitte.tms.base.masterdata.model
 * @author Hibernate Tools
 */
@Component(CustBankAccountDao.BEAN_ID)
public class CustBankAccountDaoImpl extends BaseDao<CustBankAccount> implements CustBankAccountDao{
	public DaoPage findCustBankAccountByParams(Map params, Integer pageIndex,Integer pageSize)
	{
		StringBuffer query=new StringBuffer();
		Map values=new HashMap();
		buildCustBankAccountQuery(query, values, params);
		return pageBy(query, values, pageIndex, pageSize);
	}
	public List<CustBankAccount> findCustBankAccountByParams(Map params)
	{
		StringBuffer query=new StringBuffer();
		Map values=new HashMap();
		buildCustBankAccountQuery(query, values, params);
		return findBy(query, values);
	}
	private void buildCustBankAccountQuery(StringBuffer query,Map values,Map params) {
		query.append(" from CustBankAccount where 1=1 ");
		Object value=params.get("status");
		if(AssertHelper.notEmpty(value))
		{
			query.append(" and status=:status");
			values.put("status", value);
		}
		value=params.get("customerId");
		if(AssertHelper.notEmpty(value))
		{
			query.append(" and customerId=:customerId");
			values.put("customerId", value);
		}
		value=params.get("custBankNumber");
		if(AssertHelper.notEmpty(value))
		{
			query.append(" and custBankNumber=:custBankNumber");
			values.put("custBankNumber", value);
		}
		value=params.get("deleteFlag");
		if(AssertHelper.notEmpty(value))
		{
			query.append(" and deleteFlag=:deleteFlag");
			values.put("deleteFlag", value);
		}
	}
}

