package com.deloitte.tms.pl.business.model;
// Generated 2013-3-26 15:06:34 by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;

import com.deloitte.tms.pl.business.service.rule.param.IParameter;
import com.deloitte.tms.pl.business.service.rule.param.IParameterSet;
import com.deloitte.tms.pl.core.model.impl.BaseEntity;

/**
 * BusinessParamssetset generated by hbm2java
 */
public class BusinessParamsset  extends BaseEntity implements IParameterSet{
	/**描述描述*/
    private String des;
    Long businessId;
    private Set<BusinessParams> businessParams = new HashSet<BusinessParams>(0);
    
	public Long getBusinessId() {
		return businessId;
	}
	public void setBusinessId(Long businessId) {
		this.businessId = businessId;
	}
	public String getDes() {
		return des;
	}
	public void setDes(String des) {
		this.des = des;
	}
	public Set<BusinessParams> getBusinessParams() {
		return businessParams;
	}
	public void setBusinessParams(Set<BusinessParams> businessParams) {
		this.businessParams = businessParams;
	}
	protected Long id;
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = (Long) id;
	}
	public Set<IParameter> getParameters() {
		Set<IParameter> temps = new HashSet<IParameter>();
		for(IParameter business:businessParams)
		{
			temps.add(business);
		}
		return temps;
	}

}


