package com.deloitte.tms.base.masterdata.dao;
// Generated by bo.wang with ling2.autoproject

import java.util.List;
import java.util.Map;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.dao.IDao;
import com.deloitte.tms.base.masterdata.model.TmsMdCurrencyRate;
/**
 * Home object for domain model class TmsMdCurrencyRate.
 * @see com.deloitte.tms.base.masterdata.model
 * @author Hibernate Tools
 */
public interface TmsMdCurrencyRateDao extends IDao<TmsMdCurrencyRate>{
	public static final String BEAN_ID="tmsMdCurrencyRateDao";
	public DaoPage findTmsMdCurrencyRateByParams(Map params, Integer pageIndex,Integer pageSize);
	public List<TmsMdCurrencyRate> findTmsMdCurrencyRateByParams(Map params);
}

