package com.deloitte.tms.vat.salesinvoice.service;
//Generated by bo.wang with ling2.autoproject

import java.util.Map;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.service.IService;
/**
* Home object for domain model class InvoiceTrxPool.
* @see com.deloitte.tms.vat.salesinvoice.model
* @author Hibernate Tools
*/
public interface InvoiceTrxHService extends IService {
	public static final String BEAN_ID="invoiceTrxHService";
	
	public DaoPage findInvoiceTrxHByParams(Map<String,Object> params, Integer pageIndex,Integer pageSize);
	
	
}
