package com.deloitte.tms.base.masterdata.service;
// Generated by bo.wang with ling2.autoproject

import java.util.List;
import java.util.Map;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.service.IService;
import com.deloitte.tms.base.masterdata.model.Customer;
import com.deloitte.tms.base.masterdata.model.CustomerInParam;
import com.deloitte.tms.base.masterdata.dao.CustomerDao;
/**
 * Home object for domain model class Customer.
 * @see com.deloitte.tms.base.masterdata.model
 * @author Hibernate Tools
 */
public interface CustomerService extends IService{
	public static final String BEAN_ID="customerService";
	
	public DaoPage findCustomerByParams(Map params, Integer pageIndex,Integer pageSize);
	
	public List<CustomerInParam> findCustomerByParams(Map params);
	
	public void saveCustomerDataListsMap(Map dataListsMap);
	
	public CustomerInParam convertCustomerToInParam(Customer model);
	
	public Customer convertCustomerInParamToEntity(CustomerInParam inParam);
	
	public void exeSaveCustomerInParamBatch(CustomerInParam inParam);
	
	
}

