package com.deloitte.tms.base.masterdata.service;
// Generated by bo.wang with ling2.autoproject

import java.util.List;
import java.util.Map;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.service.IService;
import com.deloitte.tms.base.masterdata.model.CustBankAccount;
import com.deloitte.tms.base.masterdata.model.CustBankAccountInParam;
import com.deloitte.tms.base.masterdata.dao.CustBankAccountDao;
/**
 * Home object for domain model class CustBankAccount.
 * @see com.deloitte.tms.base.masterdata.model
 * @author Hibernate Tools
 */
public interface CustBankAccountService extends IService{
	public static final String BEAN_ID="custBankAccountService";
	
	public DaoPage findCustBankAccountByParams(Map params, Integer pageIndex,Integer pageSize);
	
	public List<CustBankAccountInParam> findCustBankAccountByParams(Map params);
	
	public void saveCustBankAccountDataListsMap(Map dataListsMap);
	
	public CustBankAccountInParam convertCustBankAccountToInParam(CustBankAccount model);
	
	public CustBankAccount convertCustBankAccountInParamToEntity(CustBankAccountInParam inParam);
	
}

