package com.deloitte.tms.base.masterdata.service;
// Generated by bo.wang with ling2.autoproject

import java.util.List;
import java.util.Map;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.service.IService;
import com.deloitte.tms.base.masterdata.model.TmsMdLegalEntity;
import com.deloitte.tms.base.masterdata.model.TmsMdLegalInvoice;
import com.deloitte.tms.base.masterdata.model.TmsMdLegalInvoiceInParam;
import com.deloitte.tms.base.masterdata.dao.TmsMdLegalInvoiceDao;
/**
 * Home object for domain model class TmsMdLegalInvoice.
 * @see com.deloitte.tms.base.masterdata.model
 * @author Hibernate Tools
 */
public interface TmsMdLegalInvoiceService extends IService{
	public static final String BEAN_ID="tmsMdLegalInvoiceService";
	
	public DaoPage findTmsMdLegalInvoiceByParams(Map params, Integer pageIndex,Integer pageSize);
	
	public List<TmsMdLegalInvoiceInParam> findTmsMdLegalInvoiceByParams(Map params);
	
	public void saveTmsMdLegalInvoiceDataListsMap(Map dataListsMap);
	
	public TmsMdLegalInvoiceInParam convertTmsMdLegalInvoiceToInParam(TmsMdLegalInvoice model);
	
	public TmsMdLegalInvoice convertTmsMdLegalInvoiceInParamToEntity(TmsMdLegalInvoiceInParam inParam);
	
	public TmsMdLegalEntity findLegalEntity(Map<String, Object> map);
	
	public void removeTmsLegalInvoices(String[]ids);
}

