package com.deloitte.tms.base.masterdata.service;
// Generated by bo.wang with ling2.autoproject

import java.util.List;
import java.util.Map;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.service.IService;
import com.deloitte.tms.base.masterdata.model.TmsMdLegalEquipment;
import com.deloitte.tms.base.masterdata.model.TmsMdLegalEquipmentInParam;
import com.deloitte.tms.base.masterdata.dao.TmsMdLegalEquipmentDao;
import com.deloitte.tms.base.masterdata.model.TmsMdLegalEntity;
import com.deloitte.tms.base.masterdata.model.TmsMdLegalEntityInParam;
import com.deloitte.tms.base.masterdata.model.TmsMdEquipment;
import com.deloitte.tms.base.masterdata.model.TmsMdEquipmentInParam2;
/**
 * Home object for domain model class TmsMdLegalEquipment.
 * @see com.deloitte.tms.base.masterdata.model
 * @author Hibernate Tools
 */
public interface TmsMdLegalEquipmentService extends IService{
	public static final String BEAN_ID="tmsMdLegalEquipmentService";
	
	public DaoPage findTmsMdLegalEquipmentByParams(Map params, Integer pageIndex,Integer pageSize) throws Exception;
	
	public List<TmsMdLegalEquipment> findTmsMdLegalEquipmentByParams(Map params) throws Exception;
	
	public void saveTmsMdLegalEquipmentDataListsMap(Map dataListsMap) throws Exception;
	
	public TmsMdLegalEquipmentInParam convertTmsMdLegalEquipmentToInParam(TmsMdLegalEquipment model) throws Exception;
	
	public TmsMdLegalEquipment convertTmsMdLegalEquipmentInParamToEntity(TmsMdLegalEquipmentInParam inParam) throws Exception;
	
	public TmsMdLegalEntity findTmsMdLegalEntity(Map params);
	public TmsMdEquipment findTmsMdEquipment(Map params);

	public Integer runHqlOrSql(String sql, Map values);
	
	public List<TmsMdLegalEquipment> finAllEquipment();
	
	public List<TmsMdLegalEquipmentInParam> findTmsMdLegalEquipmentByParams1(Map params) throws Exception;

	public DaoPage getEquPageByRelatedLeg(String legId, int pageIndex, int pageSize);

	public DaoPage getEquPageByNoRelatedLeg(String legId, int pageIndex, int pageSize);

	public void saveBindEqu(String legalId, String[] equIds);

	public void removeEquByInfo(String legalId, String[] equIds);

	public void updateDefaultEqu(String legalId, Map defaultMap);
	
	public List<Object[]> getEquipMentListByParams(Map params);
}

