package com.deloitte.tms.base.masterdata.service;
// Generated by bo.wang with ling2.autoproject

import java.util.List;
import java.util.Map;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.service.IService;
import com.deloitte.tms.base.masterdata.model.TmsMdTaxTrxType;
import com.deloitte.tms.base.masterdata.model.TmsMdTaxTrxTypeInParam;
import com.deloitte.tms.base.masterdata.dao.TmsMdTaxTrxTypeDao;
/**
 * Home object for domain model class TmsMdTaxTrxType.
 * @see com.deloitte.tms.base.masterdata.model
 * @author Hibernate Tools
 */
public interface TmsMdTaxTrxTypeService extends IService{
	public static final String BEAN_ID="tmsMdTaxTrxTypeService";
	
	public DaoPage findTmsMdTaxTrxTypeByParams(Map params, Integer pageIndex,Integer pageSize);
	
	public List<TmsMdTaxTrxTypeInParam> findTmsMdTaxTrxTypeByParams(Map params);
	
	public void saveTmsMdTaxTrxTypeDataListsMap(Map dataListsMap);
	
	public TmsMdTaxTrxTypeInParam convertTmsMdTaxTrxTypeToInParam(TmsMdTaxTrxType model);
	
	public TmsMdTaxTrxType convertTmsMdTaxTrxTypeInParamToEntity(TmsMdTaxTrxTypeInParam inParam);

	public void removeTmsMdTaxTrxTypes(String tmsMdTaxTrxTypeId);

	public DaoPage retrievalTmsMdTaxTrxType(Map<String, Object> parameter,
			Integer pageIndex, Integer pageSize);

	
}

