package com.deloitte.tms.base.masterdata.service;
// Generated by bo.wang with ling2.autoproject

import java.util.List;
import java.util.Map;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.service.IService;
import com.deloitte.tms.base.masterdata.model.TmsMdCurrencyRate;
import com.deloitte.tms.base.masterdata.model.TmsMdCurrencyRateInParam;
import com.deloitte.tms.base.masterdata.dao.TmsMdCurrencyRateDao;
/**
 * Home object for domain model class TmsMdCurrencyRate.
 * @see com.deloitte.tms.base.masterdata.model
 * @author Hibernate Tools
 */
public interface TmsMdCurrencyRateService extends IService{
	public static final String BEAN_ID="tmsMdCurrencyRateService";
	
	public DaoPage findTmsMdCurrencyRateByParams(Map params, Integer pageIndex,Integer pageSize);
	
	public List<TmsMdCurrencyRateInParam> findTmsMdCurrencyRateByParams(Map params);
	
	public void saveTmsMdCurrencyRateDataListsMap(Map dataListsMap);
	
	public TmsMdCurrencyRateInParam convertTmsMdCurrencyRateToInParam(TmsMdCurrencyRate model);
	
	public TmsMdCurrencyRate convertTmsMdCurrencyRateInParamToEntity(TmsMdCurrencyRateInParam inParam);
	
}

