package com.deloitte.tms.vat.salesinvoice.dao;
// Generated by bo.wang with ling2.autoproject

import java.util.List;
import java.util.Map;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.dao.IDao;
import com.deloitte.tms.vat.salesinvoice.model.InvoicePriPlanSet;
/**
 * Home object for domain model class InvoicePriPlanSet.
 * @see com.deloitte.tms.vat.salesinvoice.model
 * @author Hibernate Tools
 */
public interface InvoicePriPlanSetDao extends IDao<InvoicePriPlanSet>{
	public static final String BEAN_ID="invoicePriPlanSetDao";
	public DaoPage findInvoicePriPlanSetByParams(Map params, Integer pageIndex,Integer pageSize);
	public List<InvoicePriPlanSet> findInvoicePriPlanSetByParams(Map params);
}

