package com.deloitte.tms.vat.salesinvoice.dao;
// Generated by bo.wang with ling2.autoproject

import java.util.List;
import java.util.Map;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.dao.IDao;
import com.deloitte.tms.vat.salesinvoice.model.InvoiceTrxL;
import com.deloitte.tms.vat.salesinvoice.model.InvoiceTrxL;
/**
 * Home object for domain model class InvoiceTrxL.
 * @see com.deloitte.tms.vat.salesinvoice.model
 * @author Hibernate Tools
 */
public interface InvoiceTrxLDao extends IDao<InvoiceTrxL>{
	public static final String BEAN_ID="invoiceTrxLDao";
	public DaoPage findInvoiceTrxLByParams(Map params, Integer pageIndex,Integer pageSize);

}

