package com.deloitte.tms.vat.salesinvoice.dao;
// Generated by bo.wang with ling2.autoproject

import java.util.List;
import java.util.Map;

import com.deloitte.tms.pl.core.commons.support.DaoPage;
import com.deloitte.tms.pl.core.dao.IDao;
import com.deloitte.tms.vat.salesinvoice.model.TmsCrvatInvReqBatchesL;
/**
 * Home object for domain model class TmsCrvatInvReqBatchesL.
 * @see com.deloitte.tms.vat.salesinvoice.model
 * @author Hibernate Tools
 */
public interface TmsCrvatInvReqBatchesLDao extends IDao<TmsCrvatInvReqBatchesL>{
	public static final String BEAN_ID="tmsCrvatInvReqBatchesLDao";
	public DaoPage findTmsCrvatInvReqBatchesLByParams(Map params, Integer pageIndex,Integer pageSize);
	public List<TmsCrvatInvReqBatchesL> findTmsCrvatInvReqBatchesLByParams(Map params);
}

