package com.deloitte.tms.base.taxsetting.model;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Where;

import com.deloitte.tms.base.masterdata.model.BaseOrg;
import com.deloitte.tms.base.masterdata.model.TmsMdLegalEntity;
import com.deloitte.tms.pl.core.commons.annotation.ModelProperty;
import com.deloitte.tms.pl.core.hibernate.identifier.Ling2UUIDGenerator;
import com.deloitte.tms.pl.core.model.impl.BaseEntity;
import com.deloitte.tms.vat.salesinvoice.model.InvoiceReqL;

/**
 * TmsMdOrgBsnStructures generated by ling autoproject
 */
@Entity
@Table(name=TmsMdOrgBsnStructures.TABLE)
@ModelProperty(comment="组织关联数据结构")
public class TmsMdOrgBsnStructures extends BaseEntity {

	public static final String TABLE = "TMS_MD_ORG_BSN_STRUCTURES";
	public static final String SEQ = TABLE;

    @Id
	@GenericGenerator(name=SEQ+"_GENERATOR",strategy=Ling2UUIDGenerator.STRATEGY_NAME,parameters={@Parameter(name="pkColumnValue",value=SEQ)})
	@GeneratedValue(strategy = GenerationType.TABLE, generator = SEQ+"_GENERATOR")

    @Column(name="ORG_BSN_STRUCTURES_ID")
	@ModelProperty(comment="组织关联数据结构ID")
	private String id;

    @Column(name="ORG_ID")
	@ModelProperty(comment="组织ID")
	private String orgId;

    @Column(name="ACCD_FLEX_STRUCTURES_ID")
	@ModelProperty(comment="会计数据结构定义ID")
	private String accdFlexStructuresId;

    @Column(name="LEGAL_ENTITY_ID")
	@ModelProperty(comment="纳税主体ID")
	private String legalEntityId;

    @Column(name="BSN_FLEX_STRUCTURES_ID")
	@ModelProperty(comment="业务数据结构定义ID")
	private String bsnFlexStructuresId;

    @Column(name="COST_CENTER")
	@ModelProperty(comment="成本中心")
	private String costCenter;

    @Column(name="DESCRIPTION")
	@ModelProperty(comment="备注")
	private String description;

    @Column(name="SOURCE_CODE")
	@ModelProperty(comment="来源代码_枚举值")
	private String sourceCode;

    @Column(name="START_DATE")
	@ModelProperty(comment="有效日期")
	private Date startDate;

    @Column(name="END_DATE")
	@ModelProperty(comment="失效日期")
	private Date endDate;

    @Column(name="PARENT_ID")
	@ModelProperty(comment="父结点ID")
	private String parentId;


    @ManyToOne
	@Cascade(CascadeType.REFRESH)
	@JoinColumn(name="ORG_ID", insertable=false,updatable=false,nullable=true)
    private BaseOrg baseOrg;
    
    @ManyToOne
   	@Cascade(CascadeType.REFRESH)
   	@JoinColumn(name="ACCD_FLEX_STRUCTURES_ID", insertable=false,updatable=false,nullable=true)
    private TmsMdFlexStructures tmsMdFlexStructures;
    
    
    @ManyToOne
   	@Cascade(CascadeType.REFRESH)
   	@JoinColumn(name="BSN_FLEX_STRUCTURES_ID", insertable=false,updatable=false,nullable=true)
    private TmsMdFlexStructures tmsMdFlexStructures2;
    
    @ManyToOne
   	@Cascade(CascadeType.REFRESH)
   	@JoinColumn(name="LEGAL_ENTITY_ID", insertable=false,updatable=false,nullable=true)
    private TmsMdLegalEntity tmsMdLegalEntity;
    
    
    
    
    
    
    
	public BaseOrg getBaseOrg() {
		return baseOrg;
	}

	public void setBaseOrg(BaseOrg baseOrg) {
		this.baseOrg = baseOrg;
	}

	public TmsMdFlexStructures getTmsMdFlexStructures() {
		return tmsMdFlexStructures;
	}

	public void setTmsMdFlexStructures(TmsMdFlexStructures tmsMdFlexStructures) {
		this.tmsMdFlexStructures = tmsMdFlexStructures;
	}

	public TmsMdFlexStructures getTmsMdFlexStructures2() {
		return tmsMdFlexStructures2;
	}

	public void setTmsMdFlexStructures2(TmsMdFlexStructures tmsMdFlexStructures2) {
		this.tmsMdFlexStructures2 = tmsMdFlexStructures2;
	}

	public TmsMdLegalEntity getTmsMdLegalEntity() {
		return tmsMdLegalEntity;
	}

	public void setTmsMdLegalEntity(TmsMdLegalEntity tmsMdLegalEntity) {
		this.tmsMdLegalEntity = tmsMdLegalEntity;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOrgId() {
		return orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	public String getAccdFlexStructuresId() {
		return accdFlexStructuresId;
	}

	public void setAccdFlexStructuresId(String accdFlexStructuresId) {
		this.accdFlexStructuresId = accdFlexStructuresId;
	}

	public String getLegalEntityId() {
		return legalEntityId;
	}

	public void setLegalEntityId(String legalEntityId) {
		this.legalEntityId = legalEntityId;
	}

	public String getBsnFlexStructuresId() {
		return bsnFlexStructuresId;
	}

	public void setBsnFlexStructuresId(String bsnFlexStructuresId) {
		this.bsnFlexStructuresId = bsnFlexStructuresId;
	}

	public String getCostCenter() {
		return costCenter;
	}

	public void setCostCenter(String costCenter) {
		this.costCenter = costCenter;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getSourceCode() {
		return sourceCode;
	}

	public void setSourceCode(String sourceCode) {
		this.sourceCode = sourceCode;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getParentId() {
		return parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

    
}


