package com.deloitte.tms.base.masterdata.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Where;

import com.deloitte.tms.base.taxsetting.model.TmsMdTrxAffirmSetting;
import com.deloitte.tms.pl.core.commons.annotation.ModelProperty;
import com.deloitte.tms.pl.core.hibernate.identifier.Ling2UUIDGenerator;
import com.deloitte.tms.pl.core.model.impl.BaseEntity;
import com.deloitte.tms.vat.salesinvoice.model.TmsCrvatInvReqBatchesH;
import com.deloitte.tms.vat.salesinvoice.model.TmsCrvatInvReqBatchesL;

/**
 * TmsMdTaxTrxType generated by ling autoproject
 */
@Entity
@Table(name=TmsMdTaxTrxType.TABLE)
public class TmsMdTaxTrxType implements Serializable {

	public static final String TABLE = "TMS_MD_TAX_TRX_TYPE";
	public static final String SEQ = TABLE;

    @Id
	@GenericGenerator(name=SEQ+"_GENERATOR",strategy=Ling2UUIDGenerator.STRATEGY_NAME,parameters={@Parameter(name="pkColumnValue",value=SEQ)})
	@GeneratedValue(strategy = GenerationType.TABLE, generator = SEQ+"_GENERATOR")

    @Column(name="TAX_TRX_TYPE_ID")
	@ModelProperty(comment="涉税交易类型ID")
	private String id;

    @Column(name="TAX_TRX_TYPE_CODE")
	@ModelProperty(comment="涉税交易类型编码")
	private String taxTrxTypeCode;

    @Column(name="TAX_TRX_TYPE_NAME")
	@ModelProperty(comment="涉税交易类型_枚举值")
	private String taxTrxTypeName;

    @Column(name="ORG_ID")
	@ModelProperty(comment="组织ID")
	private String orgId;

    @Column(name="ENABLED_FLAG")
	@ModelProperty(comment="是否启用")
	private Boolean enabledFlag;

    @Column(name="START_DATE")
	@ModelProperty(comment="有效日期")
	private Date startDate;

    @Column(name="END_DATE")
	@ModelProperty(comment="失效日期")
	private Date endDate;
    
    
    
    @Column(name = "CREATED_BY",  length = 50)
	@ModelProperty(comment="创建人")
	String createdBy;
	
	@Column(name = "CREATION_DATE")
	@ModelProperty(comment="创建日期/时间")
	Date createDate;
	
	@Column(name = "LAST_UPDATED_BY",  length = 50)
	@ModelProperty(comment="修改人")
	String modifiedBy;
	
	@Column(name = "LAST_UPDATE_DATE")
	@ModelProperty(comment="修改日期")
	Date modifiedDate;
	
	@Column(name = "status",  length = 10)
	@ModelProperty(comment="状态")
	String status;	
	
	@Column(name = "BIZ_ORG_CODE",  length = 36)
	@ModelProperty(comment="业务所属机构")
	String bizOrgCode;
	
	@Column(name = "OPERATION_ORG_CODE",  length = 36)
	@ModelProperty(comment="数据产生机构,")
	String operationOrgCode;
	
	@Column(name = "DATA_OWNER_CODE",  length = 36)
	@ModelProperty(comment="数据分区键")
	String dataowner;
	
	@Column(name="COMPANY_ID",length=36)
	@ModelProperty(comment="数据归属")
	String companyId;

	@Column(name="ARCHIVE_BASE_DATE")
	@ModelProperty(comment="归档基准日期")
	Date archiveBaseDate;
	
	@Column(name="RECORD_VERSION")
	@ModelProperty(comment="记录版本号，每次修改记录时加1")
	Integer versionId;
	
	@Column(name = "DELETED_FLAG",  length = 10)
	@ModelProperty(comment="删除标记",des="1==true 有效;0==false 无效")
	String flag;
	
	@Column(name="DELETED_BY",length=36)
	@ModelProperty(comment="删除人")
	String deleteBy;
	
	@Column(name="DELETION_DATE",length=36)
	@ModelProperty(comment="删除时间")
	Date deleteDate;
    
	
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTaxTrxTypeCode() {
		return taxTrxTypeCode;
	}

	public void setTaxTrxTypeCode(String taxTrxTypeCode) {
		this.taxTrxTypeCode = taxTrxTypeCode;
	}

	public String getTaxTrxTypeName() {
		return taxTrxTypeName;
	}

	public void setTaxTrxTypeName(String taxTrxTypeName) {
		this.taxTrxTypeName = taxTrxTypeName;
	}

	public String getOrgId() {
		return orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	public Boolean getEnabledFlag() {
		return enabledFlag;
	}

	public void setEnabledFlag(Boolean enabledFlag) {
		this.enabledFlag = enabledFlag;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getModifiedBy() {
		return modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedDate() {
		return modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getBizOrgCode() {
		return bizOrgCode;
	}

	public void setBizOrgCode(String bizOrgCode) {
		this.bizOrgCode = bizOrgCode;
	}

	public String getOperationOrgCode() {
		return operationOrgCode;
	}

	public void setOperationOrgCode(String operationOrgCode) {
		this.operationOrgCode = operationOrgCode;
	}

	public String getDataowner() {
		return dataowner;
	}

	public void setDataowner(String dataowner) {
		this.dataowner = dataowner;
	}

	public String getCompanyId() {
		return companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	public Date getArchiveBaseDate() {
		return archiveBaseDate;
	}

	public void setArchiveBaseDate(Date archiveBaseDate) {
		this.archiveBaseDate = archiveBaseDate;
	}

	public Integer getVersionId() {
		return versionId;
	}

	public void setVersionId(Integer versionId) {
		this.versionId = versionId;
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getDeleteBy() {
		return deleteBy;
	}

	public void setDeleteBy(String deleteBy) {
		this.deleteBy = deleteBy;
	}

	public Date getDeleteDate() {
		return deleteDate;
	}

	public void setDeleteDate(Date deleteDate) {
		this.deleteDate = deleteDate;
	}



}


